Lipis_system_master/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from Lipis_system_master import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('homepage/', views.HomePageView.as_view(), name='homepage'),
    path('application_patent_domestic/', include('application_patent_domestic.urls')),
    path('people/', include('People.urls')),
    path('management/', include('management.urls')),
    path('message/', include('message.urls')),
    path('case/', include('case.urls')),
    path('emailsystem/', include('emailsystem.urls')),
    path('changelang', views.ChangeLanguage, name='changelang'),
    path('summernote/', include('django_summernote.urls')),
    path('patentro/', include('patentro.urls')),

]

case/urls.py
from django.urls import path

from case import views, crudmodel, ajax, modelcontroller

app_name = 'case'
urlpatterns = [
    path('test', views.test, name='test'),
    path('addcasewithmsg/<pk>', views.CreateCaseWithMessage, name='addcasewithmsg'),
    path('addtaskwithmsg/<pk>', views.CreateTaskWithMessage, name='addtaskwithmsg'),
    path('case', views.CaseView.as_view(), name='cases'),
    path('case/<pk>', views.CaseDetailView.as_view(), name='cases_detail'),
    path('tasks', views.TaskView.as_view(), name='tasks'),
    path('revenue_invoices', views.RevenuInvoiceView.as_view(), name='revenue_invoices'),
    path('purchase_invoices', views.PurchaseInvoiceView.as_view(), name='purchase_invoices'),

    path('transactionhistory', views.TransactionHistoryView.as_view(), name='transactionhistory'),
    path('transactionhistory/detail/<pk>', views.TransactionHistoryDetailView.as_view(), name='transactionhistory_detail'),

    path('bankaccountinformation', views.BankAccountInformationView.as_view(), name='bankaccountinformation'),

    path('task/create', crudmodel.TaskCreate, name='createtask'),
    path('task/edit/<pk>', crudmodel.TaskEdit, name='edittask'),
    path('task/delete', crudmodel.TaskDelete, name='deletetask'),
    path('task/search/ournumner', crudmodel.Task_SearchOurCom, name='task_searchournumber'),
    path('task/create/withmasterandemailmsg', crudmodel.CreateTaskWithMasterandMsg, name='createtaskwithmasterandmsg'),
    path('task/create/popupform/<pk>', crudmodel.CustomTaskPopupForm, name='customtaskpopupform'),
    path('task/number/load', ajax.Generate_TaskNumber, name='task_number_load'),

    path('case/create', crudmodel.CaseCreate, name='createcase'),
    path('case/edit/<pk>', crudmodel.CaseEdit, name='editcase'),
    path('case/delete', crudmodel.CaseDelete, name='deletecase'),
    path('case/search/ournumner', crudmodel.Case_SearchOurCom, name='case_searchournumber'),
    path('case/number/load', ajax.Generate_CaseNumber, name='case_number_load'),
    path('case/tasktemplateref/ajax/get', ajax.GetTaskTemplateRef, name='case_tasktemplate_ref_get'),
    path('case/tasktemplate/ajax/get', ajax.GetTaskTemplate, name='case_tasktemplate_get'),
    path('case/tasktemplate/ajax/load', ajax.LoadTaskTemplate, name='case_tasktemplate_load'),

    path('case/create/withmasterandemailmsg', crudmodel.CreateCaseWithMasterandMsg, name='createcasewithmasterandmsg'),
    path('case/create/popupform/<pk>', crudmodel.CustomCasePopupForm, name='customcasepopupform'),
    path('caseortask/message/link', modelcontroller.LinkCaseOrTaskToMessage, name='linkcaseortaskmessage'),
    path('case/revenueinvoice/ajax/link', ajax.LinkCaseToRevenueInvoice, name='linkcasetorevenueinvoice'),
    path('case/finalrevenueinvoice/ajax/link', ajax.LinkFinalCaseToRevenueInvoice, name='linkfinalcasetorevenueinvoice'),
    path('case/finalrevenueinvoice/ajax/get', ajax.GetFinalRevenueInvoiceByCase, name='getfinalrevenueinvoicebycase'),
    path('case/message/ajax/unlink', ajax.UnlinkCaseToMessage, name='unlinkcasetomessage'),
    path('case/patent/bypatentourcom/ajax/get', ajax.CaseAndPatentByPatentOurCom, name='getcaseandpatent_bypatentourcom'),



    path('revenueinvoice/create', crudmodel.RevenueInvoiceCreate, name='createrevenueinvoice'),
    path('revenueinvoice/edit/<pk>', crudmodel.RevenueInvoiceEdit, name='editrevenueinvoice'),
    path('revenueinvoice/delete', crudmodel.RevenueInvoiceDelete, name='deleterevenueinvoice'),
    path('revenueinvoice/load/ourcomnumber', crudmodel.LoadOurComnumForRevenueInvoide, name='revenueinvoiceourcomnumberload'),
    path('revenueinvoice/search/ourcomnumber', ajax.SearchRevenueInvoideByOurComnum, name='revenueinvoice_search'),


    path('purchaseinvoice/create', crudmodel.PurchaseInvoiceCreate, name='createpurchaseinvoice'),
    path('purchaseinvoice/edit/<pk>', crudmodel.PurchaseInvoiceEdit, name='editpurchaseinvoice'),
    path('purchaseinvoice/delete', crudmodel.PurchaseInvoiceDelete, name='deletepurchaseinvoice'),

    path('transactionhistory/create', crudmodel.TransactionHistoryCreate, name='createtransactionhistory'),
    path('transactionhistory/edit/<pk>', crudmodel.TransactionHistoryEdit, name='edittransactionhistory'),
    path('transactionhistory/delete', crudmodel.TransactionHistoryDelete, name='deletetransactionhistory'),
    path('transactionhistory/revenue_invoce/link', ajax.LinkTransactionHistoryToRevenueInvoice, name='link_transactionhistory_revenueinvoice'),

    path('bankaccountinformation/create', crudmodel.BankAccountCreate, name='createbankaccountinformation'),
    path('bankaccountinformation/edit/<pk>', crudmodel.BankAccountEdit, name='editbankaccountinformation'),
    path('bankaccountinformation/delete', crudmodel.BankAccountDelete, name='deletebankaccountinformation'),

    path('depositinfo/ajax/set', ajax.SetDepositInfo, name='set_depositinfo'),






]

emailsystem/urls.py
from django.urls import path

from emailsystem import views, syncemail, tasks, ajax

app_name = 'emailsystem'
urlpatterns = [


    path('newemailsetting', views.savenewemail, name='newemailsetting'),
    path('syncemail', tasks.sync_email, name='syncmail'),
    path('addduplicateparentemail/<pk>', views.add_duplicate_parent_email, name='addduplicateparentemail'),
    path('deleteduplicateparentemail/<pk>', views.delete_duplicate_parent_email, name='deleteduplicateparentemail'),
    path('addduplicatechildemail/<pk>', views.add_duplicate_child_email, name='addduplicatechildemail'),
    path('deleteduplicatechildemail/<pk>', views.delete_duplicate_child_email, name='deleteduplicatechildemail'),
    path('email', views.EmailListView.as_view(), name='emaillist'),
    path('emailcontent/<pk>', views.EmailContentView.as_view(), name='email_content'),
    path('emailcontentiframe/<pk>', views.EmailContentViewForIFrame.as_view(), name='emailcontentiframe'),
    path('email/showcidimg', views.showcidimg, name='email_showcidimg'),

    path('emaildetailfilter', views.SetHTMLFilter, name ='emaildetailfilter'),
    path('emailcontent', views.EmailContentView.as_view(), name='email_content'),
    path('emailtextbodyslice/<pk>', views.EmailTextBodySlice, name='emailtextbodyslice'),
    path('emailtextbody/<pk>', views.EmailTextBody, name='emailtextbody'),

    path('emailupload', views.EmaliUploadView.as_view(), name='emailupload'),
    path('emailuploading', views.EmailFileUpload, name='emailuploading'),
    path('syncemailfile', views.sync_email_file, name='syncemailfile'),
    path('testemail', syncemail.TestEmail, name='testemail'),
    path('searchemail', views.SearchEmailView.as_view(), name='searchemail'),

    path('add_emailattach/<pk>', views.AddEmailAttach, name='add_emailattach'),
    path('linkemailmsgbyourcompanynumber', views.LinkEmailMsgByOurCompanyNumber, name='linkemailmsgbyourcompanynumber'),
    path('linkemailmsgbyapplnumber', views.LinkEmailMsgByApplNumber, name='linkemailmsgbyapplnumber'),

    path('realtimeemail', views.syncmail, name='realtimeemail'),
    path('responseemailfilter', views.result_from_email_relation_filter, name='responseemailfilter'),
    path('email/change_relation', views.change_email_relation, name='email_change_relation'),

    path('emailsetting', views.EmailSettingView.as_view(), name='emailsetting'),
    path('emailsetting/signature',views.emailsetting_signature, name='emailsetting_signature'),
    path('emailsetting/signature/<pk>',views.emailsetting_signature, name='emailsetting_signature'),
    path('emailsetting/ack',views.emailsetting_ack, name='emailsetting_ack'),
    path('emailsetting/ack/<pk>',views.emailsetting_ack, name='emailsetting_ack'),
    path('emailsetting/acksigchange', views.emailsetting_ack_sig_change, name='emailsetting_ack_sig_change'),
    path('emailsetting/emailoption/choice',views.emailsetting_emailoption_choice, name='emailsetting_emailoption_choice'),
    path('email/ack/send', views.email_ack_send, name='email_ack_send'),



]

management/urls.py
from django.urls import path

import case
import emailsystem

from emailsystem.tests import syncemail
from management import InitDB, sync_excelfile, tests, crud, ajaxs
from management import views



app_name = 'management'
urlpatterns = [
    path('customdbfilename', views.CustomDBFieldNameView.as_view(), name='custom_dbfieldname'),
    path('edit_people_fieldname', views.Edit_People_FieldView.as_view(), name='edit_people_fieldname'),
    path('test', emailsystem.tests.sendemail, name='test'),
    path('dbfieldname/init', InitDB.InitDbCustomFieldName, name='initdb_customfieldName'),
    path('dbfieldname/save', views.SaveDbCustomFieldName, name='savedb_customfieldName'),
    path('commonmgr', views.CommonMgrView.as_view(), name='common_mgr'),
    path('countrycode/save', InitDB.InitDBCountryCode, name='initdb_countrycode'),
    path('codeinfo/multiplelanguage/save', InitDB.InitDBCodeInfoMultipleLanguage, name='initdb_codeinfoformultiplelanguage'),
    path('excelupload', views.ExcelUploadView.as_view(), name='excelupload'),
    path('exceluploading', views.ExcelFileUpload, name='exceluploading'),
    path('syncexcel', sync_excelfile.sync_excel_files, name='syncexcel'),
    path('syncexcelother', sync_excelfile.sync_excel_files_other, name='syncexcel_other'),
    path('managementtest', tests.managementtest, name='managementtest'),

    path('codeinfo', views.CodeInformationView.as_view(), name='codeinfo'),
    path('codeinfo/create', views.CreateCode, name='create_codeinfo'),
    path('codeinfo/delete', views.DeleteCode, name='delete_codeinfo'),

    path('mulitplelangcode/update', views.UpdateCodeMultipleLang, name='update_multiplelanguagecode'),

    path('countrycode', views.CountryCodeInformationView.as_view(), name='countrycodeinfo'),
    path('mulitplelangcountrycode/update', views.UpdateLanguageCodeMultipleLang, name='update_multiplelanguagecountrycode'),
    path('tags', views.TagsView.as_view(), name='tags'),
    path('tags/parent/update', ajaxs.UpdateTagParent, name='tags_parent_update'),
    path('tasktemplate', views.TasksTemplateView.as_view(), name='task_template'),
    path('tasktemplateIframe', views.TaskTemplateIframeView.as_view(), name='task_template_iframe'),

    path('tasktemplate_ref/create', ajaxs.CreateTaskTemplateRef, name='create_task_template_ref'),

    path('tasktemplate/child/ajax/update', ajaxs.UpdateTemplateChild, name='update_child_task_template'),
    path('tasktemplate/state/ajax/update', ajaxs.UpdateTaskTemplateState, name='update_task_template_state'),
    path('tasktemplate/requestcasemessage/ajax/update', ajaxs.UpdateTaskTemplate_TaskRequestCaseMessage, name='update_task_template_requestcasemessage'),
    path('tasktemplate/requestreceiptmessage/ajax/update', ajaxs.UpdateTaskTemplate_TaskReceiptCaseMessage, name='update_task_template_receiptcasemessage'),
    path('tasktemplate/tag/ajax/update', ajaxs.UpdateTaskTemplate_Tag, name='update_task_template_tag'),


    path('tasktemplate/ajax/delete', ajaxs.DeleteTemplate, name='delete_task_template'),
    path('tasktemplate/ajax/create', ajaxs.CreateTaskTemplate, name='create_task_template'),
    path('tasktemplate_ref/messagetype/ajax/update', ajaxs.UpdateTemplateCaseMessageType, name='update_messagetype_tasktemplateref'),
    path('tasktemplate_ref/casestate/ajax/update', ajaxs.UpdateTemplateCaseState, name='update_casestate_tasktemplateref'),
    path('tasktemplate_ref/casestatechangecondition/ajax/update', ajaxs.UpdateTemplateCaseStateChangeCondition, name='update_casestatechangecondition_tasktemplateref'),
    path('tasktemplate_ref/ajax/get', ajaxs.GetTemplateRef, name='gettemplateref'),









]

management/forms.py
from django.forms import ModelForm
from django import forms

from application_patent_domestic.forms import ModelFormBase, BasicFormBase
from case.models import Task_Template
from management.models import DB_Modifying_Field_Name, Tag_List, Code_Information, CountryInformation
from utils.enums import ALL_CODE_TYPE


class ChangeFieldForm(ModelForm):
    class Meta:
        model = DB_Modifying_Field_Name
        fields = ['customFieldName', ]


class TagModelForm(ModelFormBase):
    def __init__(self, *args, **kwargs):
        super(TagModelForm, self).__init__(*args, **kwargs)
        if self.labeldic:
            for i, (k, v) in enumerate(self.labeldic.items()):
                self.fields[k].label = v
        if self.customcodechoice:
            self.fields['code'].choices = self.customcodechoice[ALL_CODE_TYPE.Management_TagListType.name]

    class Meta:
        model = Tag_List
        fields = '__all__'

templates/management/codeinfo.html
{% extends "management/managementbase.html" %}
{% block content %}
    {{ block.super }}
    {% regroup model_list by codeType as code_list %}
    <div class="codeul" >
         {% for key, values in codetypedic.items %}


                  <span class="codetype" >

                    {{ values }}
                <br>
            <br>
                    <div class="codenames">
                      {% for codetype, codenames in code_list %}

                {% if key == codetype %}
                    {% for code in codenames %}
                            <div><span>{{ code.codeName }}</span><span class="spandelete"> <button id="{{ code.id }}"
                                                                                              class="btn-primary"
                                                                                              onclick="deleteCode(this.id)"><i
                                class="fa fa-close"></i></button></span></div>
                    {% endfor %}
                {% endif %}
                  {% endfor %}
                    <div><input style="width: 80px" type="text" class="{{ key }}"></div>
                    <div><button style="width: 80px" class="btn btn-primary" onclick="createCode('{{ key }}')">추가
                    </button></div>
                </div>


            </span>






         {% endfor %}



    </div>

<br>
    <div style="clear: both;"><button onclick="save_all_multiplelang()">MutipleLanguage Save</button></div>
    <br>
    {% if code_list %}

        {% for codetype, codenames in code_list %}
            <table border="1">
                <tr>

                    <th></th>
                    {% for mcode in codenames.0.cml%}
                        <th>{{ mcode.languageCode }}</th>
                    {% endfor %}
                </tr>
                {% for code in codenames %}

                    <tr class="clicktr">
                        <td>{{ code.codeName }}</td>
                        {% for mcode in code.cml %}
                            <td><input type="text" value="{{ mcode.name }}" id="{{ mcode.id }}"
                                       class="multiplelangcodename"></td>
                        {% endfor %}

                    </tr>
                {% endfor %}
            </table>
        {% endfor %}


    {% endif %}

    <script>
        function save_all_multiplelang() {
            var multiplelang = document.getElementsByClassName('multiplelangcodename')

            let formData = new FormData()

            for (var i = 0; i < multiplelang.length; i++) {

                formData.append(multiplelang[i].id, multiplelang[i].value)
                //formData.append('multiplelang[1]', multiplelang[i].value)
            }
            formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
            fetch('{% url 'management:update_multiplelanguagecode' %}', {
                method: 'POST',
                body: formData,
                credentials: 'same-origin',
            })
                .then(response => {
                        alert('success.')
                        location.reload()
                    }
                )
                .catch(() => {
                    alert('fail')
                })

        }

        function createCode(codetype) {
            var codeinput = document.getElementsByClassName(codetype)
            var codeName = codeinput[0].value
            if (codeName == '') {
                return;
            }

            let formData = new FormData()

            formData.append('codeName', codeName)
            formData.append('codeType', codetype)
            formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
            fetch('{% url 'management:create_codeinfo' %}', {
                method: 'POST',
                body: formData,
                credentials: 'same-origin',
            })
                .then(response => {

                        alert('reload');
                        location.reload();
                    }
                )
                .catch(() => {
                    alert('fail')
                })
        }

        function deleteCode(codeid) {


            if (codeid == '') {
                return
            }

            let formData = new FormData()

            formData.append('pk', codeid)
            formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
            fetch('{% url 'management:delete_codeinfo' %}', {
                method: 'POST',
                body: formData,
                credentials: 'same-origin',
            })
                .then(response => {

                        location.reload()
                    }
                )
                .catch(() => {
                    alert('fail')
                })
        }
    </script>
{% endblock %}

templates/management/commoninfo_form.html
{% extends "management/managementbase.html" %}

{% block title %}{% endblock %}

{% block content %}
 {{ block.super }}

    <div class="main-container">
    <a class="button" href="{% url 'management:initdb_customfieldName' %}">다국어 DB 필드명 저장</a>
        <a class="button" href="{% url 'management:initdb_countrycode' %}">국가 코드 다국어 저장</a>
        <a class="button" href="{% url 'management:initdb_codeinfoformultiplelanguage' %}">코드 다국어 저장</a>
    <a class="button" href="{% url 'management:test' %}">이메일 보내기 테스트</a>
    <a class="button" href="{% url 'emailsystem:realtimeemail' %}">실시간이메일</a>
     <a class="button" href="{% url 'management:managementtest' %}">커스텀 테스트</a>

    </div>
    <p>TASK NAME : {{ taskinfo.task_name }}</p>
    <p>TASK STATUS : {{ taskinfo.status }}</p>
    <p>TASK LAST DONE : {{ taskinfo.date_done }}</p>
    </div>
    <p>result : {{ result }}</p>
    <style>
    p
    {
        font-size: 15px;
    }
    </style>
    <script>

   $( document ).ready(function() {


});



$(function() {



  // Handler for .ready() called.
});
    </script>
{% endblock %}

templates/management/countrycodeinfo.html
{% extends "management/managementbase.html" %}
{% block content %}
    {{ block.super }}
    <button onclick="save_all_multiplelang()">MutipleLanguage Save</button>
      <table border="1">
                <tr>

                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                {% for data in model_list %}

                    <tr class="clicktr">
                        <td>{{ data.countryCode }}</td>
                        {% for lcode in data.cml %}
                            <td><p>{{ lcode.languageCode }}</p><input type="text" value="{{ lcode.name }}" id="{{ lcode.id }}"
                                       class="multiplelangcodename"></td>
                        {% endfor %}

                    </tr>
                {% endfor %}
            </table>
    <button onclick="save_all_multiplelang()">MutipleLanguage Save</button>
    <script>
     function save_all_multiplelang() {
            var multiplelang = document.getElementsByClassName('multiplelangcodename')

            let formData = new FormData()
            var mylist = []
            for (var i = 0; i < multiplelang.length; i++) {

                if (multiplelang[i].value != null)
                {
                    var dic = {};
                    dic[multiplelang[i].id] = multiplelang[i].value;
                    mylist.push(JSON.stringify(dic));
                }
            }
            formData.append('multiplelanguage', JSON.stringify(mylist));
            formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
            fetch('{% url 'management:update_multiplelanguagecountrycode' %}', {
                method: 'POST',
                body: formData,
                credentials: 'same-origin',
            })
                .then(response => {
                        alert('success.');
                        location.reload();
                    }
                )
                .catch(() => {
                    alert('fail')
                })

        }
    </script>
{% endblock %}

templates/management/emailinfo_form.html
{% extends "management/managementbase.html" %}

{% block title %}{% endblock %}

{% block content %}
      {{ block.super }}
    <form action="" method="post">
    {%  csrf_token %}

    <input type="submit" value="save">
    </form>
{% endblock %}

templates/management/excelfileupload.html
{% extends "management/managementbase.html" %}
{% block content %}
    {{ block.super }}

    <h2>{{ _("applicantstable") }}</h2>


    <div id="drop-area">
        <form class="my-form">
            {% csrf_token %}
            <p>Upload multiple files with the file dialog or by dragging and dropping images onto the dashed
                region</p>
            <input type="file" id="fileElem" multiple accept="image/*" onchange="handleFiles(this.files)">
            <label class="button" for="fileElem">Select some files</label>
        </form>
        <div id="gallery"></div>
        <progress id="progress-bar" max=100 value=0></progress>
    </div>

    <input type="file" onchange="getfolder(event)" id="ctrl" webkitdirectory directory multiple/>
    <br>
    <div>
    {% if file_list %}
        {% for file in file_list %}
        <div >{{ file }}</div>
        {% endfor %}
    {% endif %}
    </div>
    <div>
    <a class="btn btn-primary" href="{% url 'management:syncexcel' %}">Sync Excel</a>
    <a class="btn btn-primary" href="{% url 'management:syncexcel_other' %}">Sync Excel other</a>
    </div>
    </div>
  <script type="text/javascript">


function getfolder(e) {

    var files = e.target.files;
    alert(files)
     files = [...files]
      uploadFile(files)

    //var path = files[0].webkitRelativePath;
    //var Folder = path.split("/");

}


        let uploadurl = '{% url 'management:exceluploading' %}'



        function preventDefaults(e) {
            e.preventDefault()
            e.stopPropagation()
        }

        function highlight(e) {
            dropArea.classList.add('highlight')
        }

        function unhighlight(e) {
            dropArea.classList.remove('highlight')
        }


        function handleDrop(e) {
            let dt = e.dataTransfer
            let files = dt.files

            handleFiles(files)
        }

        function handleFiles(files) {
            files = [...files]
            initializeProgress(files.length)
            uploadFile(files)
            //files.forEach(previewFile)
        }


        function uploadFile(files) {
            //let url = 'http://127.0.0.1:8000/emailsystem/emailuploading'
            let formData = new FormData()

            for (var i=0; i<files.length; i++)
                {
                    formData.append('files[]', files[i])
                }
            formData.append('csrfmiddlewaretoken', $('#csrf-helper input[name="csrfmiddlewaretoken"]').attr('value'));
            fetch(uploadurl, {
                method: 'POST',
                body: formData,
                credentials: 'same-origin',
            })
                .then(response =>
            {
                alert('success.')
                location.reload()
            }
        )
        .
            catch(() => { alert('fail')
            })
        }

        function uploadFile1(file) {
            var url = 'YOUR URL HERE'
            var xhr = new XMLHttpRequest()
            var formData = new FormData()
            xhr.open('POST', url, true)

            // Add following event listener
            xhr.upload.addEventListener("progress", function (e) {
                updateProgress(i, (e.loaded * 100.0 / e.total) || 100)
            })

            xhr.addEventListener('readystatechange', function (e) {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    // Done. Inform the user
                } else if (xhr.readyState == 4 && xhr.status != 200) {
                    // Error. Inform the user
                }
            })

            formData.append('file', file)
            xhr.send(formData)
        }

        function previewFile(file) {
            let reader = new FileReader()
            reader.readAsDataURL(file)
            reader.onloadend = function () {
                let img = document.createElement('img')
                img.src = reader.result
                document.getElementById('gallery').appendChild(img)
            }
        }


        function progressDone() {
            filesDone++
            progressBar.value = filesDone / filesToDo * 100
        }


        function initializeProgress(numFiles) {
            progressBar.value = 0
            uploadProgress = []

            for (let i = numFiles; i > 0; i--) {
                uploadProgress.push(0)
            }
        }

        function updateProgress(fileNumber, percent) {
            uploadProgress[fileNumber] = percent
            let total = uploadProgress.reduce((tot, curr) => tot + curr, 0) / uploadProgress.length
            progressBar.value = total
        }


         let dropArea = document.getElementById('drop-area')
        ;['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
            dropArea.addEventListener(eventName, preventDefaults, false)

            ;['dragenter', 'dragover'].forEach(eventName => {
                dropArea.addEventListener(eventName, highlight, false)
            })

            ;['dragleave', 'drop'].forEach(eventName => {
                dropArea.addEventListener(eventName, unhighlight, false)
            })

            dropArea.addEventListener('drop', handleDrop, false)
        })

        let filesDone = 0
        let filesToDo = 0
        let progressBar = document.getElementById('progress-bar')
    </script>
{% endblock %}

templates/management/managementbase.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="innernav">
            <span class="innermenu"><a id="commonmgrname" onclick="javascript:menuclick('commonmgrname')"
                                       href="{% url 'management:common_mgr' %}">{{ _("commonmgr") }}</a></span>


            <span class="dropdown innermenu">
      <a class="dropbtn" id="modifyfield">{{ _("editfield") }}</a>
      <div class="dropdown-content">
        <a href="{% url 'management:custom_dbfieldname' %}?fieldtype=patent_domestic"
           >출원</a>
          <a href="{% url 'management:custom_dbfieldname' %}?fieldtype=emailsystem"
             >이메일</a>
        <a href="{% url 'management:custom_dbfieldname' %}?fieldtype=people"
           >사람</a>
        <a href="{% url 'management:custom_dbfieldname' %}?fieldtype=case"
           >사건</a>
          <a href="{% url 'management:custom_dbfieldname' %}?fieldtype=message"
             >메시지</a>

      </div>


    </span>

            <span class="innermenu"><a id="syncexcel"
                                       href="{% url 'management:excelupload' %}">{{ _("syncexcel") }}</a></span>
            <span class="innermenu"><a id="codemgr"
                                       href="{% url 'management:codeinfo' %}">코드 관리</a></span>
            <span class="innermenu"><a id="countrycodemgr"
                                       href="{% url 'management:countrycodeinfo' %}">국가코드 관리</a></span>
            <span class="innermenu"><a id="tagmgr"
                                       href="{% url 'management:tags' %}">태그 관리</a></span>
            <span class="innermenu"><a id="tasktemplatemgr"
                                       href="{% url 'management:task_template' %}">사건 템플릿 관리</a></span>


        </div>
    </div>
{% endblock %}
{% block maincontent %}
{% endblock %}