Lipis_system_master/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from Lipis_system_master import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('homepage/', views.HomePageView.as_view(), name='homepage'),
    path('application_patent_domestic/', include('application_patent_domestic.urls')),
    path('people/', include('People.urls')),
    path('management/', include('management.urls')),
    path('message/', include('message.urls')),
    path('case/', include('case.urls')),
    path('emailsystem/', include('emailsystem.urls')),
    path('changelang', views.ChangeLanguage, name='changelang'),
    path('summernote/', include('django_summernote.urls')),
    path('patentro/', include('patentro.urls')),

]

case/urls.py
from django.urls import path

from case import views, crudmodel, ajax, modelcontroller

app_name = 'case'
urlpatterns = [
    path('test', views.test, name='test'),
    path('addcasewithmsg/<pk>', views.CreateCaseWithMessage, name='addcasewithmsg'),
    path('addtaskwithmsg/<pk>', views.CreateTaskWithMessage, name='addtaskwithmsg'),
    path('case', views.CaseView.as_view(), name='cases'),
    path('case/<pk>', views.CaseDetailView.as_view(), name='cases_detail'),
    path('tasks', views.TaskView.as_view(), name='tasks'),
    path('revenue_invoices', views.RevenuInvoiceView.as_view(), name='revenue_invoices'),
    path('purchase_invoices', views.PurchaseInvoiceView.as_view(), name='purchase_invoices'),

    path('transactionhistory', views.TransactionHistoryView.as_view(), name='transactionhistory'),
    path('transactionhistory/detail/<pk>', views.TransactionHistoryDetailView.as_view(), name='transactionhistory_detail'),

    path('bankaccountinformation', views.BankAccountInformationView.as_view(), name='bankaccountinformation'),

    path('task/create', crudmodel.TaskCreate, name='createtask'),
    path('task/edit/<pk>', crudmodel.TaskEdit, name='edittask'),
    path('task/delete', crudmodel.TaskDelete, name='deletetask'),
    path('task/search/ournumner', crudmodel.Task_SearchOurCom, name='task_searchournumber'),
    path('task/create/withmasterandemailmsg', crudmodel.CreateTaskWithMasterandMsg, name='createtaskwithmasterandmsg'),
    path('task/create/popupform/<pk>', crudmodel.CustomTaskPopupForm, name='customtaskpopupform'),
    path('task/number/load', ajax.Generate_TaskNumber, name='task_number_load'),

    path('case/create', crudmodel.CaseCreate, name='createcase'),
    path('case/edit/<pk>', crudmodel.CaseEdit, name='editcase'),
    path('case/delete', crudmodel.CaseDelete, name='deletecase'),
    path('case/search/ournumner', crudmodel.Case_SearchOurCom, name='case_searchournumber'),
    path('case/number/load', ajax.Generate_CaseNumber, name='case_number_load'),
    path('case/tasktemplateref/ajax/get', ajax.GetTaskTemplateRef, name='case_tasktemplate_ref_get'),
    path('case/tasktemplate/ajax/get', ajax.GetTaskTemplate, name='case_tasktemplate_get'),
    path('case/tasktemplate/ajax/load', ajax.LoadTaskTemplate, name='case_tasktemplate_load'),

    path('case/create/withmasterandemailmsg', crudmodel.CreateCaseWithMasterandMsg, name='createcasewithmasterandmsg'),
    path('case/create/popupform/<pk>', crudmodel.CustomCasePopupForm, name='customcasepopupform'),
    path('caseortask/message/link', modelcontroller.LinkCaseOrTaskToMessage, name='linkcaseortaskmessage'),
    path('case/revenueinvoice/ajax/link', ajax.LinkCaseToRevenueInvoice, name='linkcasetorevenueinvoice'),
    path('case/finalrevenueinvoice/ajax/link', ajax.LinkFinalCaseToRevenueInvoice, name='linkfinalcasetorevenueinvoice'),
    path('case/finalrevenueinvoice/ajax/get', ajax.GetFinalRevenueInvoiceByCase, name='getfinalrevenueinvoicebycase'),
    path('case/message/ajax/unlink', ajax.UnlinkCaseToMessage, name='unlinkcasetomessage'),
    path('case/patent/bypatentourcom/ajax/get', ajax.CaseAndPatentByPatentOurCom, name='getcaseandpatent_bypatentourcom'),



    path('revenueinvoice/create', crudmodel.RevenueInvoiceCreate, name='createrevenueinvoice'),
    path('revenueinvoice/edit/<pk>', crudmodel.RevenueInvoiceEdit, name='editrevenueinvoice'),
    path('revenueinvoice/delete', crudmodel.RevenueInvoiceDelete, name='deleterevenueinvoice'),
    path('revenueinvoice/load/ourcomnumber', crudmodel.LoadOurComnumForRevenueInvoide, name='revenueinvoiceourcomnumberload'),
    path('revenueinvoice/search/ourcomnumber', ajax.SearchRevenueInvoideByOurComnum, name='revenueinvoice_search'),


    path('purchaseinvoice/create', crudmodel.PurchaseInvoiceCreate, name='createpurchaseinvoice'),
    path('purchaseinvoice/edit/<pk>', crudmodel.PurchaseInvoiceEdit, name='editpurchaseinvoice'),
    path('purchaseinvoice/delete', crudmodel.PurchaseInvoiceDelete, name='deletepurchaseinvoice'),

    path('transactionhistory/create', crudmodel.TransactionHistoryCreate, name='createtransactionhistory'),
    path('transactionhistory/edit/<pk>', crudmodel.TransactionHistoryEdit, name='edittransactionhistory'),
    path('transactionhistory/delete', crudmodel.TransactionHistoryDelete, name='deletetransactionhistory'),
    path('transactionhistory/revenue_invoce/link', ajax.LinkTransactionHistoryToRevenueInvoice, name='link_transactionhistory_revenueinvoice'),

    path('bankaccountinformation/create', crudmodel.BankAccountCreate, name='createbankaccountinformation'),
    path('bankaccountinformation/edit/<pk>', crudmodel.BankAccountEdit, name='editbankaccountinformation'),
    path('bankaccountinformation/delete', crudmodel.BankAccountDelete, name='deletebankaccountinformation'),

    path('depositinfo/ajax/set', ajax.SetDepositInfo, name='set_depositinfo'),






]

case/models.py
from django.core.exceptions import ValidationError
from django.db import models
# Create your models here.
from management.models import BaseModel
from utils.enums import INVOICE_TYPE, CASE_TASK_TYPE, EXTERNALSERVICE_MESSAGE_TYPE, \
    MakeCurrencyEnum, TASK_PROCEDURE_TYPE, CASE_TYPE, TASK_TYPE, CASE_STATE, TASK_STATE, REVENUE_INVOICE_STATE, \
    PURCHASE_INVOICE_STATE, MESSAGE_CASETASK_TYPE


class Case(BaseModel):

    master = models.ManyToManyField(
        'application_patent_domestic.Application_Patent_Domestic_Master',
        through='application_patent_domestic.Application_Patent_Domestic_Master_Case',
        related_name='case_master', blank=True
    )


    caseNumber = models.CharField(max_length=50, null=True, blank=True)
    caseCode = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=30, null=True, blank=True)
    receptionDate = models.DateTimeField(null=True, blank=True)
    isNeedSendReport = models.BooleanField(null=True, blank=True)
    isNeedSubmissionReport = models.BooleanField(null=True, blank=True)
    recentCaseDocumentSubmissionDate = models.DateTimeField(null=True, blank=True)
    initialCaseDocumentSubmissionDueDate = models.DateTimeField(null=True, blank=True)
    recentCaseDocumentSubmissionDueDate = models.DateTimeField(null=True, blank=True)
    recentSubmissionInstructionReceiptDate = models.DateTimeField(null=True, blank=True)
    recentCompleteReportDate = models.DateTimeField(null=True, blank=True)

    case_client = models.ManyToManyField(
        'People.Client',
        through='Case_Task_Invoice_Management',
        related_name='case_client', blank=True
    )
    case_clientmanagement = models.ManyToManyField(
        'People.Person',
        through='Case_Task_Invoice_Management',
        related_name='case_client_manager', blank=True
    )
    case_ourcompanymanagement = models.ManyToManyField(
        'People.Person',
        through='Case_OurCompanyManagement',
        related_name='case_ourcompanymanager', blank=True
    )
    task = models.ManyToManyField(
        'Task',
        through='Case_Task',
        related_name='case_task', blank=True
    )
    message = models.ManyToManyField(
        'message.Message',
        through='Case_Task_Message',
        related_name='case_message', blank=True
    )

    final_revenue_invoice = models.ForeignKey('Revenue_Invoice', null=True, blank=True, on_delete=models.SET_NULL,
                              related_name='case_finalrevenueinvoice')
    def __str__(self):
        if self.caseNumber:
            return self.caseNumber
        else:
            return 'no case number. case id is {}'.format(self.id)


    class Meta:
        db_table = "case"

class Task(BaseModel):

    master = models.ManyToManyField(
        'application_patent_domestic.Application_Patent_Domestic_Master',
            through='application_patent_domestic.Application_Patent_Domestic_Master_Task',
        related_name='task_master', blank=True
    )

    taskNumber = models.CharField(max_length=50, null=True, blank=True)
    taskCode = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=30, null=True, blank=True)
    receptionDate = models.DateTimeField(null=True, blank=True)
    completionReportingDate = models.DateTimeField(null=True, blank=True)
    neededCompletionReporting = models.BooleanField(null=True, blank=True)
    isChargedExpense = models.BooleanField(null=True, blank=True)
    internalCompletionDueDate = models.DateTimeField(null=True, blank=True)
    completionDueDate = models.DateTimeField(null=True, blank=True)
    chargedExpense = models.CharField(max_length=50, null=True, blank=True)
    chargedExpenseCurrency = models.CharField(max_length=50, null=True, blank=True)
    externalServiceRequest = models.DateTimeField(null=True, blank=True)
    externalServiceResultsReceptionDate = models.DateTimeField(null=True, blank=True)
    externalServicePrice = models.CharField(max_length=50, null=True, blank=True)
    externalServicePriceCurrency = models.CharField(max_length=50, null=True, blank=True)
    task_client = models.ManyToManyField('People.Client', through='Case_Task_Invoice_Management', related_name='task_client', blank=True)
    task_clientmanagement = models.ManyToManyField('People.Person', through='Case_Task_Invoice_Management', related_name='task_clientmanagement', blank=True)
    externalservice_client = models.ManyToManyField('People.Client', through='Task_ExternalService', related_name='task_externalservice_client', blank=True)
    externalservice_clientmanagement = models.ManyToManyField('People.Person', through='Task_ExternalService',
                                                    related_name='task_externalservice_clientmanagement', blank=True)

    externalService_message = models.ManyToManyField('message.Message', through='Task_ExternalService_Message', related_name='task_externalservice_message',blank=True)
    purchase_invoice = models.ForeignKey('Purchase_Invoice', null=True, blank=True, related_name='task_purchase_invoice', on_delete=models.SET_NULL)
    case = models.ManyToManyField(
        'Case',
        through='Case_Task',
        related_name='task_case', blank=True
    )
    child = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL,
                              related_name='task_child')
    def __str__(self):
        if self.taskNumber:
            return self.taskNumber
        else:
            return self.taskCode
    class Meta:
        db_table = "task"


class Case_Task(models.Model):
    case = models.ForeignKey('Case', blank=False, related_name='case_task_case', on_delete=models.CASCADE)
    task = models.ForeignKey('Task', blank=False, related_name='case_task_task', on_delete=models.CASCADE)
    class Meta:
        db_table = "case_task"



class Revenue_Invoice(BaseModel):
    ourCompanyNumber = models.CharField(max_length=50, null=True, blank=True)
    ourCompanyClaimNumber = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=30, null=True, blank=True)
    case = models.ForeignKey('Case', on_delete=models.SET_NULL, related_name='case_revenueinvoice', null=True, blank=True)
    claimDate = models.DateTimeField(null=True, blank=True)
    totalCharges = models.DecimalField(max_digits=15, decimal_places=0, default=0)
    chargesCurrency = models.CharField(max_length=50, null=True, blank=True, choices=[(tag.value, tag.value) for tag in MakeCurrencyEnum()])
    ourCompanyCharges = models.DecimalField(max_digits=15, decimal_places=0, default=0)
    vat = models.DecimalField(max_digits=15, decimal_places=0, default=0)
    taxInvoiceIssueDate = models.DateTimeField(null=True, blank=True)
    depositDate = models.DateTimeField(null=True, blank=True)
    totalDepositAmount = models.DecimalField(max_digits=15, decimal_places=0, default=0)
    totalDepositAmountCurrency = models.CharField(max_length=50, null=True, blank=True,choices=[(tag.value, tag.value) for tag in MakeCurrencyEnum()])
    paymentCompletionDate = models.DateTimeField(null=True, blank=True)
    revenue_invoice_client = models.ManyToManyField('People.Client', through='Case_Task_Invoice_Management',
                                         related_name='revenue_invoice_client')
    revenue_invoice_clientmanagement = models.ManyToManyField('People.Person', through='Case_Task_Invoice_Management',
                                                   related_name='revenue_invoice_clientmanagement')
    revenue_deposit_info = models.ManyToManyField('Transaction_History', through='Deposit_List',
                                                   related_name='revenue_deposit_list', blank=True)
    class Meta:
        db_table = "revenue_invoice"

class Purchase_Invoice(BaseModel):
    purchaseCompanyClaimNumber = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=30, null=True, blank=True)
    claimDate = models.DateTimeField(null=True, blank=True)
    invoiceReceptionDate = models.DateTimeField(null=True, blank=True)
    totalCharges = models.DecimalField(max_digits=15, decimal_places=0, default=0)
    chargesCurrency = models.CharField(max_length=50, null=True, blank=True, choices=[(tag.value, tag.value) for tag in MakeCurrencyEnum()])
    vat = models.DecimalField(max_digits=15, decimal_places=0, default=0)
    taxInvoiceIssueDate = models.DateTimeField(null=True, blank=True)
    depositDate = models.DateTimeField(null=True, blank=True)
    totalDepositAmount = models.DecimalField(max_digits=15, decimal_places=0, default=0)
    totalDepositAmountCurrency = models.CharField(max_length=50, null=True, blank=True, choices=[(tag.value, tag.value) for tag in MakeCurrencyEnum()])
    paymentCompletionDate = models.DateTimeField(null=True, blank=True)
    purchase_invoice_client = models.ManyToManyField('People.Client', through='Case_Task_Invoice_Management',
                                         related_name='purchase_invoice_client')
    purchase_invoice_clientmanagement = models.ManyToManyField('People.Person', through='Case_Task_Invoice_Management',
                                                   related_name='purchase_invoice_clientmanagement')
    purchase_deposit_info = models.ManyToManyField('Transaction_History', through='Deposit_List',
                                                  related_name='purchase_deposit_list', blank=True)

    class Meta:
        db_table = "purchase_invoice"

class Case_Task_Invoice_Management(models.Model):
    case = models.ForeignKey('Case', on_delete=models.CASCADE, related_name='case_task_invoice_management_case',null=True, blank=True)
    task = models.ForeignKey('Task', on_delete=models.CASCADE, related_name='case_task_invoice_management_task',null=True, blank=True)

templates/case/add_case_form.html
{% extends "popupformbase.html" %}

{% block title %}{% endblock %}

{% block formblock %}
    <input hidden name="msgid" value="{{ msgid }}">
        <p>메시지 타입</p>
     <select name="casetype" >
            {% for case in casetype %}
                <option value="{{ case.value }}">
                    {{ case.value }}</option>
            {% endfor %}
        </select>

    {{ form.as_p }}
{% endblock %}

templates/case/bankaccountinformation.html
{% extends "case/casebase.html" %}
{% block content %}
    {{ block.super }}
    <h2>계좌정보</h2>
     <table border="1" class="model_list">
                <tr>
                    <th>
                        <input id="checkall" type="checkbox" value="">
                    </th>
                    <th>{{ _("edit") }}</th>

                        <th>{{ model_list.0.bankName }}</th>
                        <th>{{ model_list.0.accountNumber }}</th>
                        <th>{{ model_list.0.depositorName }}</th>
                        <th>{{ model_list.0.isClientInfo }}</th>


                </tr>
                {% if model_list.1 %}
                    {% for data in model_list.1 %}
                        <tr class="clicktr" data-id="{{ data.id }}" id="">
                            <td class="checked">
                                <a href="JavaScript:deleteModel('{% url 'case:deletebankaccountinformation' %}','{{ data.id }}');">삭제</a>
                            </td>
                            <td class="clicktrexcept">
                                <a href="JavaScript:newPopup('{% url 'case:editbankaccountinformation' data.id %}');">{{ _("edit") }}</a>
                            </td>

                            <td>{{ data.bankName }}</td>
                            <td>{{ data.accountNumber }}</td>
                            <td>{{ data.depositorName }}</td>
                            <td>{{ data.isClientInfo }}</td>

                        </tr>
                    {% endfor %}
                {% else %}
                    <td>{{ _("nodata") }}</td>
                {% endif %}
            </table>


            <span class="tableopt">
                <a class="btn btn-primary"
                   onclick="newPopup('{% url 'case:createbankaccountinformation' %}')">{{ _("create") }}</a>
            </span>
            <br>
        </form>
        <span class="pagination">
        <span class="step-links">
        {% if model_list.1.has_previous %}
            <a href="?page=1">&laquo; {{ _("first") }}</a>

            <a href="?page={{ model_list.1.previous_page_number }}">{{ _("previous") }}</a>
        {% endif %}

            <span class="current">
            Page {{ model_list.1.number }} of {{ model_list.1.paginator.num_pages }}.
        </span>

            {% if model_list.1.has_next %}
                <a href="?page={{ model_list.1.next_page_number }}">{{ _("next") }}</a>
                <a href="?page={{ model_list.1.paginator.num_pages }}">{{ _("last") }} &raquo;</a>
            {% endif %}
        </span>
            </span>
{% endblock %}

templates/case/bankaccountinformation_form.html
{% extends "popupformbase.html" %}

{% block title %}{% endblock %}

{% block formblock %}

    {{ form.as_p }}
{% endblock %}

templates/case/case_form.html
{% extends "popupformbase.html" %}

{% block title %}{% endblock %}

{% block formblock %}

    {{ form.as_p }}

        <script>

        $(document).ready(function () {
            if ('{{ serialnum }}') {
                $("#id_caseNumber").val('{{ serialnum }}')
                var today = new Date();
                var dd = String(today.getDate()).padStart(2, '0');
                var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
                var yyyy = today.getFullYear();
                var year = yyyy+'-'+ mm + '-' + dd
                $("#id_receptionDate").val(year)
                $("#id_caseCode").val('{{ serialnum }}'.slice(1,4))
            }
            //$("#id_patentType option:eq(1)").attr('selected','selected');

        })

        $("#id_caseCode")
            .change(function () {
                var txt = $("select#id_caseCode option:selected").val();
                var ournum = $("#id_caseNumber").val()
                if (txt != '' & ournum.length == 13) {

                    var newournum = ournum.slice(0, 1) + txt + ournum.slice(4, 13)
                    var ournumforsearch = newournum.slice(0, 10)
                    Ajax_for_searchourcom(ournumforsearch)


                }

            })


        $("#id_receptionDate")
                .change(function () {
                    var ourcomnumber = $("#id_caseNumber").val();
                    var selectedyear =  $("#id_receptionDate").val();

                if (selectedyear != '' & ourcomnumber.length == 13) {


                    var newournum = ourcomnumber.slice(0, 4) + selectedyear.slice(2,4) + selectedyear.slice(5,7)+selectedyear.slice(8,10)
                    Ajax_for_searchourcom(newournum)
                }

            })
        function Ajax_for_searchourcom(ournumforsearch) {
            $.ajax({
                url: '{% url 'case:case_searchournumber' %}',
                data: {
                    'searchournum': ournumforsearch
                },
                dataType: 'json',
                success: function (data) {

                    $("#id_caseNumber").val(data.serialnum)
                }
            });
        }

        //id_ourCompanyNumber
    </script>
{% endblock %}

templates/case/linkcase_master_message_form.html
{% extends "popupformbase.html" %}

{% block title %}{% endblock %}

{% block formblock %}
    {% load emailsystem_tags %}
    {% if type %}
        {% include_email_case_form_forpatentdoc linkmsg form caseevidencefile %}

    {% else %}
        {% include_email_case_form linkmsg form caseevidencefile %}
    {% endif %}
{% endblock %}

templates/case/linktask_master_message_form.html
{% extends "popupformbase.html" %}

{% block title %}{% endblock %}

{% block formblock %}
{% load emailsystem_tags %}
{% include_email_task_form linkmsg form %}
{% endblock %}

templates/case/purchase_invoice_form.html
{% extends "popupformbase.html" %}

{% block title %}{% endblock %}

{% block formblock %}

    {{ form.as_p }}
{% endblock %}

templates/case/task_form.html
{% extends "popupformbase.html" %}

{% block title %}{% endblock %}

{% block formblock %}

    {{ form.as_p }}

     <script>

        $(document).ready(function () {
            if ('{{ serialnum }}') {
                $("#id_taskNumber").val('{{ serialnum }}')
                var today = new Date();
                var dd = String(today.getDate()).padStart(2, '0');
                var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
                var yyyy = today.getFullYear();
                var year = yyyy+'-'+ mm + '-' + dd
                $("#id_receptionDate").val(year)
                $("#id_taskCode").val('{{ serialnum }}'.slice(1,5))
            }
            //$("#id_patentType option:eq(1)").attr('selected','selected');

        })

        $("#id_taskCode")
            .change(function () {
                var txt = $("select#id_taskCode option:selected").val();
                var ournum = $("#id_taskNumber").val()
                if (txt != '' & ournum.length == 15) {

                    var newournum = ournum.slice(0, 1) + txt + ournum.slice(5, 15)
                    var ournumforsearch = newournum.slice(0, 11)
                    Ajax_for_searchourcom(ournumforsearch)


                }

            }).change();


        $("#id_receptionDate")
                .change(function () {
                    var ourcomnumber = $("#id_taskNumber").val();
                    var selectedyear =  $("#id_receptionDate").val();

                if (selectedyear != '' & ourcomnumber.length == 13) {


                    var newournum = ourcomnumber.slice(0, 5) + selectedyear.slice(2,4) + selectedyear.slice(5,7) + selectedyear.slice(8,10)
                    Ajax_for_searchourcom(newournum)
                }

            }).change();
        function Ajax_for_searchourcom(ournumforsearch) {
            $.ajax({
                url: '{% url 'case:task_searchournumber' %}',
                data: {
                    'searchournum': ournumforsearch
                },
                dataType: 'json',
                success: function (data) {

                    $("#id_taskNumber").val(data.serialnum)
                }
            });
        }

        //id_ourCompanyNumber
    </script>
{% endblock %}

templates/case/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>




<aa class='aa' >



</body>
<style>

.aa{

width:100%;

height:500px;

background-attachment:fixed;

background-image:url('01.png');

}
</style>
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<script type="text/javascript">

	$(window).scroll(function(e){

		parallax();

	});



	function parallax(){

		var scrolled = $(window).scrollTop();

		$('.aa').css('background-position-y',-(scrolled*0.4)+'px');

	}

</script>



</html>

templates/case/transactionhistory.html
{% extends "case/casebase.html" %}
{% block content %}
    {{ block.super }}
    <h2>거래내역</h2>
     <table border="1" class="model_list basictable">
                <tr>
                    <th>
                        <input id="checkall" type="checkbox" value="">
                    </th>
                    <th>{{ _("edit") }}</th>

                        <th>{{ model_list.0.order }}</th>
                        <th>{{ model_list.0.transactionDate}}</th>
                        <th>{{ model_list.0.breifs }}</th>
                        <th>{{ model_list.0.recipient }}</th>
                        <th>{{ model_list.0.currency }}</th>
                        <th>{{ model_list.0.depositAmount }}</th>
                         <th>{{ model_list.0.withdrawalAmount }}</th>
                        <th>{{ model_list.0.balance }}</th>
                        <th>{{ model_list.0.type }}</th>
                        <th>{{ model_list.0.transactionOffice }}</th>
                        <th>{{ model_list.0.client_receiver }}</th>


                </tr>
                {% if model_list.1 %}
                    {% for data in model_list.1 %}
                        <tr class="clicktr" data-id="{% url 'case:transactionhistory_detail' data.id %}" id="">
                            <td class="checked">
                                <a href="JavaScript:deleteModel('{% url 'case:deletetransactionhistory' %}','{{ data.id }}');">삭제</a>
                            </td>
                            <td class="clicktrexcept">
                                <a href="JavaScript:newPopup('{% url 'case:edittransactionhistory' data.id %}');">{{ _("edit") }}</a>
                            </td>

                            <td>{{ data.order }}</td>
                            <td>{{ data.transactionDate|date:"Y-m-d H:i:s"  }}</td>
                            <td>{{ data.breifs }}</td>
                            <td>{{ data.recipient }}</td>
                            <td>{{ data.currency }}</td>

                            <td>{{ data.depositAmount }}</td>
                            <td>{{ data.withdrawalAmount }}</td>
                             <td>{{ data.balance }}</td>
                         <td>{{ data.type }}</td>
                        <td>{{ data.transactionOffice }}</td>
                        <td>{% for cm in data.client_receiver.all %}
                            {{ cm }}
                        {% endfor %}
                        </td>



                        </tr>
                    {% endfor %}
                {% else %}
                    <td>{{ _("nodata") }}</td>
                {% endif %}
            </table>


            <span class="tableopt">
                <a class="btn btn-primary"
                   onclick="newPopup('{% url 'case:createtransactionhistory' %}')">{{ _("create") }}</a>
            </span>
            <br>
        </form>
        <span class="pagination">
        <span class="step-links">
        {% if model_list.1.has_previous %}
            <a href="?page=1">&laquo; {{ _("first") }}</a>

            <a href="?page={{ model_list.1.previous_page_number }}">{{ _("previous") }}</a>
        {% endif %}

            <span class="current">
            Page {{ model_list.1.number }} of {{ model_list.1.paginator.num_pages }}.
        </span>

            {% if model_list.1.has_next %}
                <a href="?page={{ model_list.1.next_page_number }}">{{ _("next") }}</a>
                <a href="?page={{ model_list.1.paginator.num_pages }}">{{ _("last") }} &raquo;</a>
            {% endif %}
        </span>
            </span>
    <script>
     $(document).on("dblclick", "td", function () {
            var clickedBtnID = $(this).attr('class');
            if (clickedBtnID != 'clicktrexcept') {   //e.preventDefault();
                var did = $(this).parent().attr('data-id');
                location.href = did
            }

        });
    </script>
{% endblock %}