Lipis_system_master/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from Lipis_system_master import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('homepage/', views.HomePageView.as_view(), name='homepage'),
    path('application_patent_domestic/', include('application_patent_domestic.urls')),
    path('people/', include('People.urls')),
    path('management/', include('management.urls')),
    path('message/', include('message.urls')),
    path('case/', include('case.urls')),
    path('emailsystem/', include('emailsystem.urls')),
    path('changelang', views.ChangeLanguage, name='changelang'),
    path('summernote/', include('django_summernote.urls')),
    path('patentro/', include('patentro.urls')),

]

People/urls.py
from django.urls import path

from People import views, crudmodel, account, ajax

app_name = 'People'
urlpatterns = [

    path('client', views.ClientView.as_view(), name='client'),
    path('client/create', crudmodel.ClientCreate, name='client_create'),
    path('client/edit/<pk>', crudmodel.ClientEdit, name='client_edit'),
    path('client/delete', crudmodel.ClientDelete, name='client_delete'),

    path('applicantinformation', views.ApplicantInformationView.as_view(), name='applicantinformation'),
    path('applicantinformation/create', crudmodel.ApplicantInformationCreate, name='create_applicantinformation'),
    path('applicantinformation/edit/<pk>', crudmodel.ApplicantInformationEdit, name='edit_applicantinformation'),
    path('applicantinformation/delete', crudmodel.ApplicantInformationDelete, name='delete_applicantinformation'),

    path('person/<int:pk>', views.PersonDetailView.as_view(), name='person_detail'),
    path('person', views.PersonView.as_view(), name='person'),
    path('person/workemail/search', crudmodel.SearchEmail, name='person_workemail_search'),
    path('person/workemail/link', ajax.person_email_link, name='person_workemail_link'),


    path('person/create', crudmodel.PersonCreate, name='person_create'),
    path('person/edit/<pk>', crudmodel.PersonEdit, name='person_edit'),
    path('person/delete', crudmodel.PersonDelete, name='person_delete'),

    path('emailcontact', views.EmailContactView.as_view(), name='emailcontact'),
    path('emailcontact/create', crudmodel.WorkEmailCreate, name='emailcontact_create'),
    path('emailcontact/edit/<pk>', crudmodel.WorkEmailEdit, name='emailcontact_edit'),
    path('emailcontact/delete', crudmodel.WorkEmailDelete, name='emailcontact_delete'),

    path('workemail/save/person/link', crudmodel.save_workemail_person_link, name='workemail_save_peson_link'),
    path('workemail/person/unlink', ajax.workemail_person_unlink, name='workemail_peson_unlink'),

    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.Logout, name='logout'),



]

application_patent_domestic/urls.py
from django.urls import path
from application_patent_domestic import crudmodel, ajax
from sync_file import kipo_goods
from . import views



app_name = 'application_patent_domestic'
urlpatterns = [
    path('patentmaster', views.MasterView.as_view(), name='patent_master'),
    path('master/create', crudmodel.MasterCreate, name='master_create'),
    path('master/edit/<pk>', crudmodel.MasterEdit, name='master_edit'),
    path('master/delete', crudmodel.MasterDelete, name='master_delete'),
    path('master/<pk>', views.MasterDetailView.as_view(), name='master_detail'),
    path('master/search/ourcom', crudmodel.Master_SearchOurCom, name='master_search_ourcom'),
    path('master/relation/get', ajax.GetMasterRelation, name='master_relation_get'),
    path('master/filter/ajax/set', ajax.SetMasterFilter, name='master_filter_set'),


    path('applicant', views.ApplicantsView.as_view(), name='applicant'),
    path('applicant/create', crudmodel.ApplicantCreate, name='applicant_create'),
    path('applicant/edit/<pk>', crudmodel.ApplicantEdit, name='applicant_edit'),
    path('applicant/delete', crudmodel.ApplicantDelete, name='applicant_delete'),
    path('applicant/addmaster', views.LinkPatentMasterApplicant, name='applicant_addmaster'),
    path('applicant/deletemaster', views.DelLinkPatentMasterApplicant, name='applicant_deletemaster'),
    path('upload_brandimage/<pk>', views.UploadBrandImage, name='upload_brandimage'),
    path('inventorview', views.MainInventorView.as_view(), name='inventorview'),
    path('maininventor/create', crudmodel.MainInventorCreate, name='maininventor_create'),
    path('maininventor/edit/<pk>', crudmodel.MainInventorEdit, name='maininventor_edit'),
    path('maininventor/delete', crudmodel.MainInventorDelete, name='maininventor_delete'),

    path('agentview', views.AgentView.as_view(), name='agentview'),
    path('agent/create', crudmodel.AgentCreate, name='agent_create'),
    path('agent/edit/<pk>', crudmodel.AgentEdit, name='agent_edit'),
    path('agent/delete', crudmodel.AgentDelete, name='agent_delete'),

    path('kipogoods', views.KIPOGoodsView.as_view(), name='kipo_goods'),
    path('kipogoods/sync', views.KIPOGoodsSyncView.as_view(), name='kipo_goods_sync'),
    path('kipogoods/fileupload', views.KIPOGoodsExcelFileUpload, name='kipo_goods_fileupload'),
    path('kipogoods/filesync', kipo_goods.sync_kipogoods, name='kipo_goods_filesync')

]

case/urls.py
from django.urls import path

from case import views, crudmodel, ajax, modelcontroller

app_name = 'case'
urlpatterns = [
    path('test', views.test, name='test'),
    path('addcasewithmsg/<pk>', views.CreateCaseWithMessage, name='addcasewithmsg'),
    path('addtaskwithmsg/<pk>', views.CreateTaskWithMessage, name='addtaskwithmsg'),
    path('case', views.CaseView.as_view(), name='cases'),
    path('case/<pk>', views.CaseDetailView.as_view(), name='cases_detail'),
    path('tasks', views.TaskView.as_view(), name='tasks'),
    path('revenue_invoices', views.RevenuInvoiceView.as_view(), name='revenue_invoices'),
    path('purchase_invoices', views.PurchaseInvoiceView.as_view(), name='purchase_invoices'),

    path('transactionhistory', views.TransactionHistoryView.as_view(), name='transactionhistory'),
    path('transactionhistory/detail/<pk>', views.TransactionHistoryDetailView.as_view(), name='transactionhistory_detail'),

    path('bankaccountinformation', views.BankAccountInformationView.as_view(), name='bankaccountinformation'),

    path('task/create', crudmodel.TaskCreate, name='createtask'),
    path('task/edit/<pk>', crudmodel.TaskEdit, name='edittask'),
    path('task/delete', crudmodel.TaskDelete, name='deletetask'),
    path('task/search/ournumner', crudmodel.Task_SearchOurCom, name='task_searchournumber'),
    path('task/create/withmasterandemailmsg', crudmodel.CreateTaskWithMasterandMsg, name='createtaskwithmasterandmsg'),
    path('task/create/popupform/<pk>', crudmodel.CustomTaskPopupForm, name='customtaskpopupform'),
    path('task/number/load', ajax.Generate_TaskNumber, name='task_number_load'),

    path('case/create', crudmodel.CaseCreate, name='createcase'),
    path('case/edit/<pk>', crudmodel.CaseEdit, name='editcase'),
    path('case/delete', crudmodel.CaseDelete, name='deletecase'),
    path('case/search/ournumner', crudmodel.Case_SearchOurCom, name='case_searchournumber'),
    path('case/number/load', ajax.Generate_CaseNumber, name='case_number_load'),
    path('case/tasktemplateref/ajax/get', ajax.GetTaskTemplateRef, name='case_tasktemplate_ref_get'),
    path('case/tasktemplate/ajax/get', ajax.GetTaskTemplate, name='case_tasktemplate_get'),
    path('case/tasktemplate/ajax/load', ajax.LoadTaskTemplate, name='case_tasktemplate_load'),

    path('case/create/withmasterandemailmsg', crudmodel.CreateCaseWithMasterandMsg, name='createcasewithmasterandmsg'),
    path('case/create/popupform/<pk>', crudmodel.CustomCasePopupForm, name='customcasepopupform'),
    path('caseortask/message/link', modelcontroller.LinkCaseOrTaskToMessage, name='linkcaseortaskmessage'),
    path('case/revenueinvoice/ajax/link', ajax.LinkCaseToRevenueInvoice, name='linkcasetorevenueinvoice'),
    path('case/finalrevenueinvoice/ajax/link', ajax.LinkFinalCaseToRevenueInvoice, name='linkfinalcasetorevenueinvoice'),
    path('case/finalrevenueinvoice/ajax/get', ajax.GetFinalRevenueInvoiceByCase, name='getfinalrevenueinvoicebycase'),
    path('case/message/ajax/unlink', ajax.UnlinkCaseToMessage, name='unlinkcasetomessage'),
    path('case/patent/bypatentourcom/ajax/get', ajax.CaseAndPatentByPatentOurCom, name='getcaseandpatent_bypatentourcom'),



    path('revenueinvoice/create', crudmodel.RevenueInvoiceCreate, name='createrevenueinvoice'),
    path('revenueinvoice/edit/<pk>', crudmodel.RevenueInvoiceEdit, name='editrevenueinvoice'),
    path('revenueinvoice/delete', crudmodel.RevenueInvoiceDelete, name='deleterevenueinvoice'),
    path('revenueinvoice/load/ourcomnumber', crudmodel.LoadOurComnumForRevenueInvoide, name='revenueinvoiceourcomnumberload'),
    path('revenueinvoice/search/ourcomnumber', ajax.SearchRevenueInvoideByOurComnum, name='revenueinvoice_search'),


    path('purchaseinvoice/create', crudmodel.PurchaseInvoiceCreate, name='createpurchaseinvoice'),
    path('purchaseinvoice/edit/<pk>', crudmodel.PurchaseInvoiceEdit, name='editpurchaseinvoice'),
    path('purchaseinvoice/delete', crudmodel.PurchaseInvoiceDelete, name='deletepurchaseinvoice'),

    path('transactionhistory/create', crudmodel.TransactionHistoryCreate, name='createtransactionhistory'),
    path('transactionhistory/edit/<pk>', crudmodel.TransactionHistoryEdit, name='edittransactionhistory'),
    path('transactionhistory/delete', crudmodel.TransactionHistoryDelete, name='deletetransactionhistory'),
    path('transactionhistory/revenue_invoce/link', ajax.LinkTransactionHistoryToRevenueInvoice, name='link_transactionhistory_revenueinvoice'),

    path('bankaccountinformation/create', crudmodel.BankAccountCreate, name='createbankaccountinformation'),
    path('bankaccountinformation/edit/<pk>', crudmodel.BankAccountEdit, name='editbankaccountinformation'),
    path('bankaccountinformation/delete', crudmodel.BankAccountDelete, name='deletebankaccountinformation'),

    path('depositinfo/ajax/set', ajax.SetDepositInfo, name='set_depositinfo'),






]

emailsystem/urls.py
from django.urls import path

from emailsystem import views, syncemail, tasks, ajax

app_name = 'emailsystem'
urlpatterns = [


    path('newemailsetting', views.savenewemail, name='newemailsetting'),
    path('syncemail', tasks.sync_email, name='syncmail'),
    path('addduplicateparentemail/<pk>', views.add_duplicate_parent_email, name='addduplicateparentemail'),
    path('deleteduplicateparentemail/<pk>', views.delete_duplicate_parent_email, name='deleteduplicateparentemail'),
    path('addduplicatechildemail/<pk>', views.add_duplicate_child_email, name='addduplicatechildemail'),
    path('deleteduplicatechildemail/<pk>', views.delete_duplicate_child_email, name='deleteduplicatechildemail'),
    path('email', views.EmailListView.as_view(), name='emaillist'),
    path('emailcontent/<pk>', views.EmailContentView.as_view(), name='email_content'),
    path('emailcontentiframe/<pk>', views.EmailContentViewForIFrame.as_view(), name='emailcontentiframe'),
    path('email/showcidimg', views.showcidimg, name='email_showcidimg'),

    path('emaildetailfilter', views.SetHTMLFilter, name ='emaildetailfilter'),
    path('emailcontent', views.EmailContentView.as_view(), name='email_content'),
    path('emailtextbodyslice/<pk>', views.EmailTextBodySlice, name='emailtextbodyslice'),
    path('emailtextbody/<pk>', views.EmailTextBody, name='emailtextbody'),

    path('emailupload', views.EmaliUploadView.as_view(), name='emailupload'),
    path('emailuploading', views.EmailFileUpload, name='emailuploading'),
    path('syncemailfile', views.sync_email_file, name='syncemailfile'),
    path('testemail', syncemail.TestEmail, name='testemail'),
    path('searchemail', views.SearchEmailView.as_view(), name='searchemail'),

    path('add_emailattach/<pk>', views.AddEmailAttach, name='add_emailattach'),
    path('linkemailmsgbyourcompanynumber', views.LinkEmailMsgByOurCompanyNumber, name='linkemailmsgbyourcompanynumber'),
    path('linkemailmsgbyapplnumber', views.LinkEmailMsgByApplNumber, name='linkemailmsgbyapplnumber'),

    path('realtimeemail', views.syncmail, name='realtimeemail'),
    path('responseemailfilter', views.result_from_email_relation_filter, name='responseemailfilter'),
    path('email/change_relation', views.change_email_relation, name='email_change_relation'),

    path('emailsetting', views.EmailSettingView.as_view(), name='emailsetting'),
    path('emailsetting/signature',views.emailsetting_signature, name='emailsetting_signature'),
    path('emailsetting/signature/<pk>',views.emailsetting_signature, name='emailsetting_signature'),
    path('emailsetting/ack',views.emailsetting_ack, name='emailsetting_ack'),
    path('emailsetting/ack/<pk>',views.emailsetting_ack, name='emailsetting_ack'),
    path('emailsetting/acksigchange', views.emailsetting_ack_sig_change, name='emailsetting_ack_sig_change'),
    path('emailsetting/emailoption/choice',views.emailsetting_emailoption_choice, name='emailsetting_emailoption_choice'),
    path('email/ack/send', views.email_ack_send, name='email_ack_send'),



]

People/forms.py
from django.forms import ModelForm

from People.models import *
from django import forms

from application_patent_domestic.forms import ModelFormBase
from common.codemultilanguage_choice import MakeTagChoiceMultipleLanguage
from utils.enums import ALL_CODE_TYPE


class ClientModelForm(ModelFormBase):
	def __init__(self, *args, **kwargs):
		super(ClientModelForm, self).__init__(*args, **kwargs)
		if self.labeldic:
			for i, (k, v) in enumerate(self.labeldic.items()):
				if k != 'createdDate':
					self.fields[k].label = v
		if self.customcodechoice:
			self.fields['client_clienttype'].choices = self.customcodechoice[ALL_CODE_TYPE.Client_Type.name]
			MakeTagChoiceMultipleLanguage(self)


	class Meta:
		model = Client
		fields = '__all__'

class PersonModelForm(ModelFormBase):
	def __init__(self, *args, **kwargs):
		self.after_create_history = True
		super(PersonModelForm, self).__init__(*args, **kwargs)
		if self.labeldic:
			for i, (k, v) in enumerate(self.labeldic.items()):

				self.fields[k].label = v
		self.fields['company'].queryset = Client.objects.all()
		ModelFormBase.arrange_and_createtablehistory(self)


	class Meta:
		model = Person
		fields = '__all__'

class WorkEmailModelForm(ModelFormBase):
	def __init__(self, *args, **kwargs):
		super(WorkEmailModelForm, self).__init__(*args, **kwargs)
		if self.labeldic:
			for i, (k,v) in enumerate(self.labeldic.items()):
				self.fields[k].label = v

	class Meta:
		model = Work_Email
		fields = '__all__'

class ApplicantInformationModelForm(ModelFormBase):
	def __init__(self, *args, **kwargs):
		super(ApplicantInformationModelForm, self).__init__(*args, **kwargs)
		if self.labeldic:
			for i, (k,v) in enumerate(self.labeldic.items()):
				if k != 'creationDate':
					self.fields[k].label = v


	class Meta:
		model = ApplicantInformation
		fields = '__all__'




class LoginForm(forms.Form):
	emailId = forms.CharField(widget=forms.EmailInput)
	password = forms.CharField(widget=forms.PasswordInput)

templates/People/applicantinformation_form.html
{% extends "popupformbase.html" %}

{% block title %}{% endblock %}

{% block formblock %}
   {{ form.as_p }}
{% endblock %}

templates/People/applicantinformations.html
{% extends "People/peoplesbase.html" %}
{% block content %}
    {{ block.super }}

    <h2>{{_("clienttable")}}</h2>

    <div>
        <table border="1" class="client_list">
            <tr>
                <th>
                    <input id="checkall" type="checkbox" value="">
                </th>
                <th>{{_("edit")}}</th>
                <th>{{  model_list.0.code}}</th>
                <th>{{  model_list.0.past_id}}</th>
                <th>{{  model_list.0.creationDate}}</th>
                <th>{{  model_list.0.isCorporation}}</th>
                <th>{{  model_list.0.isCompany}}</th>
                <th>{{  model_list.0.originLastName}}</th>
                <th>{{  model_list.0.originFirstName}}</th>
                <th>{{  model_list.0.originFullName}}</th>
                <th>{{  model_list.0.originAddress}}</th>
                <th>{{  model_list.0.engLastName}}</th>
                <th>{{  model_list.0.engFirstName}}</th>
                <th>{{  model_list.0.engFullName}}</th>
                <th>{{  model_list.0.engAddress}}</th>
                <th>{{  model_list.0.korLastName}}</th>
                <th>{{  model_list.0.korFirstName}}</th>
                <th>{{  model_list.0.korFullName}}</th>
                <th>{{  model_list.0.korAddress}}</th>



            </tr>
            {% if model_list.1 %}
                {% for data in model_list.1 %}
                    <tr data-id="{{ data.id }}">
                        <td class="checked">
                           <a href="JavaScript:deleteModel('{% url 'People:delete_applicantinformation'%}')">삭제</a>
                        </td>
                        <td>
                            <a href="JavaScript:newPopup('{% url 'People:edit_applicantinformation' data.id %}');">{{_("edit")}}</a>
                        </td>
                     <td>{{ data.code }}</td>
                    <td>{{ data.past_id }}</td>
                    <td>{{ data.creationDate }}</td>
                    <td>{{ data.isCorporation }}</td>
                    <td>{{ data.isCompany }}</td>
                    <td>{{ data.originLastName }}</td>
                    <td>{{ data.originFirstName }}</td>
                    <td>{{ data.originFullName }}</td>
                    <td>{{ data.originAddress }}</td>
                    <td>{{ data.engLastName }}</td>
                    <td>{{ data.engFirstName }}</td>
                    <td>{{ data.engFullName }}</td>
                    <td>{{ data.engAddress }}</td>
                    <td>{{ data.korLastName }}</td>
                    <td>{{ data.korFirstName }}</td>
                    <td>{{ data.korFullName }}</td>
                    <td>{{ data.korAddress }}</td>


                    </tr>
                {% endfor %}
            {% else %}
                <td>{{_("nodata")}}</td>
            {% endif %}
        </table>
        <span class="pagination">
        <span class="step-links">
        {% if model_list.1.has_previous %}
            <a href="?page=1">&laquo; {{ _("first") }}</a>

            <a href="?page={{ model_list1.1.previous_page_number }}">{{ _("previous") }}</a>
        {% endif %}

            <span class="current">
            Page {{ model_list.1.number }} of {{ model_list.1.paginator.num_pages }}.
        </span>

            {% if model_list.1.has_next %}
                <a href="?page={{ model_list.1.next_page_number }}">{{ _("next") }}</a>
                <a href="?page={{ model_list.1.paginator.num_pages }}">{{ _("last") }} &raquo;</a>
            {% endif %}
        </span>
            </span>
        <span class="tableopt">
            <a class="btn btn-primary" onclick="newPopup('{% url 'People:create_applicantinformation' %}')">{{_("create")}}</a>
        </span>
    </div>

{% endblock %}

templates/People/emailcontact.html
{% extends "People/peoplesbase.html" %}
{% block content %}
    {{ block.super }}



    <div>
        <table border="1" class="client_list">
            <tr>
                <th>
                    <input id="checkall" type="checkbox" value="">
                </th>
                <th>{{_("edit")}}</th>
                <th>이메일주소</th>
                <th>이름</th>

            </tr>
            {% if model_list.1 %}
                {% for data in model_list.1 %}
                    <tr data-id="{{ data.id }}">
                        <td class="checked">
                           <a href="JavaScript:deleteModel('{% url 'People:emailcontact_delete'%}')">삭제</a>
                        </td>
                        <td>
                            <a href="JavaScript:newPopup('{% url 'People:emailcontact_edit' data.id %}');">{{_("edit")}}</a>
                        </td>

                    <td>{{ data.email }}</td>
                    <td>{{ data.emailName }}</td>


                    </tr>
                {% endfor %}
            {% else %}
                <td>{{_("nodata")}}</td>
            {% endif %}
        </table>
      <span class="pagination">
        <span class="step-links">
        {% if model_list.1.has_previous %}
            <a href="?page=1">&laquo; {{ _("first") }}</a>

            <a href="?page={{ model_list.1.previous_page_number }}">{{ _("previous") }}</a>
        {% endif %}

            <span class="current">
            Page {{ model_list.1.number }} of {{ model_list.1.paginator.num_pages }}.
        </span>

            {% if model_list.1.has_next %}
                <a href="?page={{ model_list.1.next_page_number }}">{{ _("next") }}</a>
                <a href="?page={{ model_list.1.paginator.num_pages }}">{{ _("last") }} &raquo;</a>
            {% endif %}
        </span>
            </span>

      <span class="tableopt">
            <a class="btn btn-primary" onclick="newPopup('{% url 'People:emailcontact_create' %}')">{{_("create")}}</a>
        </span>
    </div>

{% endblock %}

templates/People/peoplesbase.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        {% block mainnav %}
             <div class="innernav">
             <span><a id="client"  href="{% url 'People:client' %}?ClientType=Client">{{_("client")}}</a></span>
                 <span><a id="oversea_agent"  href="{% url 'People:client' %}?ClientType=OverseaAgent">해외대리인</a></span>
                <span><a id="applicants"  href="{% url 'application_patent_domestic:applicant' %}">{{_("applicants")}}</a></span>

                 <span><a id="applicantinformation"  href="{% url 'People:applicantinformation' %}">출원인정보</a></span>

                <span><a id="person"  href="{% url 'People:person' %}">{{_("person")}}</a></span>
             <span><a id="maininventor"  href="{% url 'application_patent_domestic:inventorview' %}">발명자</a></span>
             <span><a id="agent" href="{% url 'application_patent_domestic:agentview' %}">에이전트</a></span>
             <span><a id="emailcontact"  href="{% url 'People:emailcontact' %}">이메일연락처</a></span>

           </div>
        {% endblock %}
    </div>
{% endblock %}

templates/People/person.html
{% extends "People/peoplesbase.html" %}
{% block content %}
    {{ block.super }}

    <h2>사람</h2>

    <div>
        <table border="1" class="model_list basictable">
            <tr>
                <th>
                    <input id="checkall" type="checkbox" value="">
                </th>

                <th>{{ _("edit") }}</th>
                <th>{{ model_list.0.companyName }}</th>
                <th>성명</th>
                <th>이메일주소</th>
                <th>{{ model_list.0.department }}</th>
                <th>{{ model_list.0.position }}</th>
                <th>{{ model_list.0.phoneNumber }}</th>
                <th>{{ model_list.0.companyPhoneNumber }}</th>


            </tr>
            {% if model_list.1 %}
                {% for data in model_list.1 %}
                    <tr data-id="{% url 'People:person_detail' data.id %}">
                        <td class="clicktrexcept">
                            <a href="JavaScript:deleteModel('{% url 'People:person_delete' %}','{{ data.id }}')">삭제</a>
                        </td>
                        <td class="clicktrexcept">
                            <a href="JavaScript:newPopup('{% url 'People:person_edit' data.id %}');">{{ _("edit") }}</a>
                        </td>

                        <td>{% for client in data.company.all %}
                            {{ client }}
                        {% endfor %}
                        </td>
                        <td>
                            {{ data }}
                        </td>
                        <td>{% for em in data.workemail_person.all %}
                            <p>{{ em }} <button class="btn btn-primary" onclick="unlink_person_email('{{ em.id }}')">unlink</button></p>
                        {% endfor %}

                            <div>
         <span class="ui-widget">
        <label for="search_email">이메일검색: </label>
        <input class="search_email" id="{{ data.id }}">
    </span>
                                <form method="post" action="{% url 'People:workemail_save_peson_link' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="pk" value="{{ data.id }}">
                                    <br>
                                    <label>직접 입력</label>
                                    <br>
                                    <span>
                                    <label>주소</label>
                                    <input type="email" name="email">
                                    </span>
                                    <br>
                                    <span>
                                    <label>이름</label>
                                    <input type="text" name="name">
                                    <p><input type="submit" value="저장"></p>
                                </span>
                                </form>
                            </div>
                        </td>
                        <td>{{ data.department }}</td>
                        <td>{{ data.position }}</td>
                        <td>{{ data.phoneNumber }}</td>
                        <td>{{ data.companyPhoneNumber }}</td>


                    </tr>
                {% endfor %}
            {% else %}
                <td>{{ _("nodata") }}</td>
            {% endif %}
        </table>
        <span class="pagination">
        <span class="step-links">
        {% if model_list.1.has_previous %}
            <a href="?page=1">&laquo; {{ _("first") }}</a>

            <a href="?page={{ model_list.1.previous_page_number }}">{{ _("previous") }}</a>
        {% endif %}

            <span class="current">
            Page {{ model_list.1.number }} of {{ model_list.1.paginator.num_pages }}.
        </span>

            {% if model_list.1.has_next %}
                <a href="?page={{ model_list.1.next_page_number }}">{{ _("next") }}</a>
                <a href="?page={{ model_list.1.paginator.num_pages }}">{{ _("last") }} &raquo;</a>
            {% endif %}
        </span>
            </span>
        <span class="tableopt">
            <a class="btn btn-primary" onclick="newPopup('{% url 'People:person_create' %}')">{{ _("create") }}</a>

        </span>
    </div>
    <style>
        .ui-autocomplete {
            max-width: 300px !important;
            max-height: 600px;
            overflow-y: auto; /* prevent horizontal scrollbar */
            overflow-x: hidden; /* add padding to account for vertical scrollbar */
            z-index: 1000 !important;
        }
    </style>
    <script>

        $(document).on("dblclick", "td", function () {

            var clickedBtnID = $(this).attr('class');
            if (clickedBtnID != 'clicktrexcept') {   //e.preventDefault();
                var did = $(this).parent().attr('data-id');
                MoveLocation(did);
            }

        });
        function unlink_person_email(pk) {

            $.ajax({
                url: '{% url 'People:workemail_peson_unlink' %}',
                data: {'pk': pk},
                type: 'GET',
                dataType: 'json',
                success: function (data) {

                    if (data.state == 'success') {
                        location.reload();

                    } else {
                        alert(data.result);
                    }

                }
            });
        }

        function link_person_email(workemail, pk) {

            $.ajax({
                url: '{% url 'People:person_workemail_link' %}',
                data: {'workemail': workemail, 'pk': pk},
                type: 'GET',
                dataType: 'json',
                success: function (data) {

                    if (data.state == 'success') {
                        location.reload();

                    } else {
                        alert(data.result);
                    }

                }
            });
        }

        $(function () {


            $(".search_email").autocomplete({

                source: '{% url 'People:person_workemail_search' %}',

                select: function (event, ui) {

                    var pid = $(this).attr('id')
                    console.log(pid)
                    link_person_email(ui.item.value, pid)


                },

                focus: function (event, ui) {

                    return false;

                    //event.preventDefault();

                }

            });
        });
    </script>
{% endblock %}