Lipis_system_master/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from Lipis_system_master import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('homepage/', views.HomePageView.as_view(), name='homepage'),
    path('application_patent_domestic/', include('application_patent_domestic.urls')),
    path('people/', include('People.urls')),
    path('management/', include('management.urls')),
    path('message/', include('message.urls')),
    path('case/', include('case.urls')),
    path('emailsystem/', include('emailsystem.urls')),
    path('changelang', views.ChangeLanguage, name='changelang'),
    path('summernote/', include('django_summernote.urls')),
    path('patentro/', include('patentro.urls')),

]

case/urls.py
from django.urls import path

from case import views, crudmodel, ajax, modelcontroller

app_name = 'case'
urlpatterns = [
    path('test', views.test, name='test'),
    path('addcasewithmsg/<pk>', views.CreateCaseWithMessage, name='addcasewithmsg'),
    path('addtaskwithmsg/<pk>', views.CreateTaskWithMessage, name='addtaskwithmsg'),
    path('case', views.CaseView.as_view(), name='cases'),
    path('case/<pk>', views.CaseDetailView.as_view(), name='cases_detail'),
    path('tasks', views.TaskView.as_view(), name='tasks'),
    path('revenue_invoices', views.RevenuInvoiceView.as_view(), name='revenue_invoices'),
    path('purchase_invoices', views.PurchaseInvoiceView.as_view(), name='purchase_invoices'),

    path('transactionhistory', views.TransactionHistoryView.as_view(), name='transactionhistory'),
    path('transactionhistory/detail/<pk>', views.TransactionHistoryDetailView.as_view(), name='transactionhistory_detail'),

    path('bankaccountinformation', views.BankAccountInformationView.as_view(), name='bankaccountinformation'),

    path('task/create', crudmodel.TaskCreate, name='createtask'),
    path('task/edit/<pk>', crudmodel.TaskEdit, name='edittask'),
    path('task/delete', crudmodel.TaskDelete, name='deletetask'),
    path('task/search/ournumner', crudmodel.Task_SearchOurCom, name='task_searchournumber'),
    path('task/create/withmasterandemailmsg', crudmodel.CreateTaskWithMasterandMsg, name='createtaskwithmasterandmsg'),
    path('task/create/popupform/<pk>', crudmodel.CustomTaskPopupForm, name='customtaskpopupform'),
    path('task/number/load', ajax.Generate_TaskNumber, name='task_number_load'),

    path('case/create', crudmodel.CaseCreate, name='createcase'),
    path('case/edit/<pk>', crudmodel.CaseEdit, name='editcase'),
    path('case/delete', crudmodel.CaseDelete, name='deletecase'),
    path('case/search/ournumner', crudmodel.Case_SearchOurCom, name='case_searchournumber'),
    path('case/number/load', ajax.Generate_CaseNumber, name='case_number_load'),
    path('case/tasktemplateref/ajax/get', ajax.GetTaskTemplateRef, name='case_tasktemplate_ref_get'),
    path('case/tasktemplate/ajax/get', ajax.GetTaskTemplate, name='case_tasktemplate_get'),
    path('case/tasktemplate/ajax/load', ajax.LoadTaskTemplate, name='case_tasktemplate_load'),

    path('case/create/withmasterandemailmsg', crudmodel.CreateCaseWithMasterandMsg, name='createcasewithmasterandmsg'),
    path('case/create/popupform/<pk>', crudmodel.CustomCasePopupForm, name='customcasepopupform'),
    path('caseortask/message/link', modelcontroller.LinkCaseOrTaskToMessage, name='linkcaseortaskmessage'),
    path('case/revenueinvoice/ajax/link', ajax.LinkCaseToRevenueInvoice, name='linkcasetorevenueinvoice'),
    path('case/finalrevenueinvoice/ajax/link', ajax.LinkFinalCaseToRevenueInvoice, name='linkfinalcasetorevenueinvoice'),
    path('case/finalrevenueinvoice/ajax/get', ajax.GetFinalRevenueInvoiceByCase, name='getfinalrevenueinvoicebycase'),
    path('case/message/ajax/unlink', ajax.UnlinkCaseToMessage, name='unlinkcasetomessage'),
    path('case/patent/bypatentourcom/ajax/get', ajax.CaseAndPatentByPatentOurCom, name='getcaseandpatent_bypatentourcom'),



    path('revenueinvoice/create', crudmodel.RevenueInvoiceCreate, name='createrevenueinvoice'),
    path('revenueinvoice/edit/<pk>', crudmodel.RevenueInvoiceEdit, name='editrevenueinvoice'),
    path('revenueinvoice/delete', crudmodel.RevenueInvoiceDelete, name='deleterevenueinvoice'),
    path('revenueinvoice/load/ourcomnumber', crudmodel.LoadOurComnumForRevenueInvoide, name='revenueinvoiceourcomnumberload'),
    path('revenueinvoice/search/ourcomnumber', ajax.SearchRevenueInvoideByOurComnum, name='revenueinvoice_search'),


    path('purchaseinvoice/create', crudmodel.PurchaseInvoiceCreate, name='createpurchaseinvoice'),
    path('purchaseinvoice/edit/<pk>', crudmodel.PurchaseInvoiceEdit, name='editpurchaseinvoice'),
    path('purchaseinvoice/delete', crudmodel.PurchaseInvoiceDelete, name='deletepurchaseinvoice'),

    path('transactionhistory/create', crudmodel.TransactionHistoryCreate, name='createtransactionhistory'),
    path('transactionhistory/edit/<pk>', crudmodel.TransactionHistoryEdit, name='edittransactionhistory'),
    path('transactionhistory/delete', crudmodel.TransactionHistoryDelete, name='deletetransactionhistory'),
    path('transactionhistory/revenue_invoce/link', ajax.LinkTransactionHistoryToRevenueInvoice, name='link_transactionhistory_revenueinvoice'),

    path('bankaccountinformation/create', crudmodel.BankAccountCreate, name='createbankaccountinformation'),
    path('bankaccountinformation/edit/<pk>', crudmodel.BankAccountEdit, name='editbankaccountinformation'),
    path('bankaccountinformation/delete', crudmodel.BankAccountDelete, name='deletebankaccountinformation'),

    path('depositinfo/ajax/set', ajax.SetDepositInfo, name='set_depositinfo'),






]

emailsystem/urls.py
from django.urls import path

from emailsystem import views, syncemail, tasks, ajax

app_name = 'emailsystem'
urlpatterns = [


    path('newemailsetting', views.savenewemail, name='newemailsetting'),
    path('syncemail', tasks.sync_email, name='syncmail'),
    path('addduplicateparentemail/<pk>', views.add_duplicate_parent_email, name='addduplicateparentemail'),
    path('deleteduplicateparentemail/<pk>', views.delete_duplicate_parent_email, name='deleteduplicateparentemail'),
    path('addduplicatechildemail/<pk>', views.add_duplicate_child_email, name='addduplicatechildemail'),
    path('deleteduplicatechildemail/<pk>', views.delete_duplicate_child_email, name='deleteduplicatechildemail'),
    path('email', views.EmailListView.as_view(), name='emaillist'),
    path('emailcontent/<pk>', views.EmailContentView.as_view(), name='email_content'),
    path('emailcontentiframe/<pk>', views.EmailContentViewForIFrame.as_view(), name='emailcontentiframe'),
    path('email/showcidimg', views.showcidimg, name='email_showcidimg'),

    path('emaildetailfilter', views.SetHTMLFilter, name ='emaildetailfilter'),
    path('emailcontent', views.EmailContentView.as_view(), name='email_content'),
    path('emailtextbodyslice/<pk>', views.EmailTextBodySlice, name='emailtextbodyslice'),
    path('emailtextbody/<pk>', views.EmailTextBody, name='emailtextbody'),

    path('emailupload', views.EmaliUploadView.as_view(), name='emailupload'),
    path('emailuploading', views.EmailFileUpload, name='emailuploading'),
    path('syncemailfile', views.sync_email_file, name='syncemailfile'),
    path('testemail', syncemail.TestEmail, name='testemail'),
    path('searchemail', views.SearchEmailView.as_view(), name='searchemail'),

    path('add_emailattach/<pk>', views.AddEmailAttach, name='add_emailattach'),
    path('linkemailmsgbyourcompanynumber', views.LinkEmailMsgByOurCompanyNumber, name='linkemailmsgbyourcompanynumber'),
    path('linkemailmsgbyapplnumber', views.LinkEmailMsgByApplNumber, name='linkemailmsgbyapplnumber'),

    path('realtimeemail', views.syncmail, name='realtimeemail'),
    path('responseemailfilter', views.result_from_email_relation_filter, name='responseemailfilter'),
    path('email/change_relation', views.change_email_relation, name='email_change_relation'),

    path('emailsetting', views.EmailSettingView.as_view(), name='emailsetting'),
    path('emailsetting/signature',views.emailsetting_signature, name='emailsetting_signature'),
    path('emailsetting/signature/<pk>',views.emailsetting_signature, name='emailsetting_signature'),
    path('emailsetting/ack',views.emailsetting_ack, name='emailsetting_ack'),
    path('emailsetting/ack/<pk>',views.emailsetting_ack, name='emailsetting_ack'),
    path('emailsetting/acksigchange', views.emailsetting_ack_sig_change, name='emailsetting_ack_sig_change'),
    path('emailsetting/emailoption/choice',views.emailsetting_emailoption_choice, name='emailsetting_emailoption_choice'),
    path('email/ack/send', views.email_ack_send, name='email_ack_send'),



]

message/urls.py
from django.urls import path
from message import views, crudmodel, requests, ajax

app_name = 'message'
urlpatterns = [




    path('patentdocumsg', views.PatentDocuMessageView.as_view(), name='patentdocumsg'),
    path('patentsubmitdocumsg', views.PatentSubmitDocuMessageView.as_view(), name='patentsubmitdocumsg'),
    path('patentdocuupload', views.PatentDocuUploadView.as_view(), name='patentdocuupload'),
    path('patentdocu/uploading', requests.PatentDocuFileUploading, name='patentdocuuploading'),
    path('patentdocu/sync', requests.sync_patentdocu, name='syncpatentdocu'),

    path('patentsubmitdocuupload', views.PatentSubmitDocuUploadView.as_view(), name='patentdocusubmitupload'),
    path('patentsubmitdocu/uploading', ajax.PatentSubmitDocuFileUploading, name='patentsubmitdocu_uploading'),
    path('patentsubmitdocu/ajax/patent/get', ajax.PatentSubmitDocuGetPatent, name='patentsubmitdocu_patent_get'),
    path('patentsubmitdocu/patent/sync', crudmodel.patent_submit_docu_patent_sync, name='patentsubmitdocu_patent_sync'),


    path('emailmessage', views.EmailMessageView.as_view(), name='emailmessage'),


    path('searchemailmessage', views.SearchEmailMessageView.as_view(), name='searchemailmessage'),

    path('selectfromemailmessage', views.SelectFromEmailMessageView.as_view(), name='selectfromemailmessage'),

    path('searchmasterinemailmessage/<pk>', views.GetMasterInEmailMessage, name='searchmasterinemailmessage'),
    path('searchinmaster/<pk>', views.SearchInMaster, name='searchinmaster'),
    path('linkpatentmastermessage', views.LinkPatentMasterMessage, name='linkpatentmastermessage'),
    path('dellinkpatentmastermessage', views.DelLinkPatentMasterMessage, name='dellinkpatentmastermessage'),
    path('setclassfied', views.SetClassfied, name='setclassfied'),
    path('message/emailiframe/setclassfied', views.EmailIframeSetClassfied, name='emailiframe_setclassfied'),

    path('addattachmentdraganddropview/<pk>', views.AddEmailAttachmentUploadView.as_view(), name='addattachmentdraganddropview'),
    path('addattachment/<pk>', views.AddAttachment, name='addattachment'),
    path('classifyingallmsg', views.ClassfyingAll, name='classifyingallmsg'),

    path('messagemgr', views.MessageManagementView.as_view(), name='messagemgr'),
    path('messagemgr/create', crudmodel.MessageCreate, name='create_messagemgr'),
    path('messagemgr/edit/<pk>', crudmodel.MessageEdit, name='edit_messagemgr'),
    path('messagemgr/delete', crudmodel.MessageDelete, name='delete_messagemgr'),
    path('messagemgr/search/ournumber', crudmodel.SearchOurComnumForMessage, name='searchournumber_messagemgr'),
    path('message/patent/edit/<pk>', crudmodel.MessageEditForPatent, name='message_patent_edit')



]

templates/forinclude/email_detail/root_include_email_detail.html
<label>html</label>
<select onchange="javascript:changeHTML('{% url 'emailsystem:emaildetailfilter' %}',this.value)">

    <option value="True" {% if ishtml == 'True' %}selected="selected"{% endif %}>True</option>
    <option value="False" {% if ishtml == 'False' %}selected="selected"{% endif %}>False</option>
</select>
<br>
<span class="emailtitle">보낸 날짜 : </span><span> {{ emaildetail.sentDate|date:"Y-m-d H:i:s" }}</span>
<br>
<br>
<span class="emailtitle">보낸 사람 : </span>
<span title="{{ emaildetail.fromEmail.email }}">{{ emaildetail.fromEmail.emailName }}</span>
<br>
<br>
<span> <span class="emailtitle">받는 사람 : </span>
    {% for to in emaildetail.to_person.all %}
        <span title="{{ to.email }}">{{ to.emailName }} ,</span>
    {% endfor %}</span>
<br>
<br>
<span class="emailtitle">제목 :</span> <span>{{ emaildetail.subject }}</span>
<br>
<span class="emailtitle">첨부파일 :</span>
<span>
{% for file in emaildetail.email_file.all %}
    <a href="{{ file.path.url }}">{{ file.originFileName }}</a>
{% endfor %}
</span>
<input type="file" onchange="getfile(event,'{% url 'emailsystem:add_emailattach' emaildetail.id %}')" id="ctrl"/>
</span>
<br>
<br>
<div>
     <p class="emailtitle">분류된 출원
        <button id="{{ emaildetail.msg }}"
                onclick="popupdialogbox(this,'{% url 'message:searchmasterinemailmessage' emaildetail.msg %}')">검색
        </button>
    </p>
    {% for m in master %}
        <p><span>당소번호 : {{ m.ourCompanyNumber }}
            <button class="btn btn-primary"
                    onclick="linkwithMaster('{% url 'emailsystem:linkemailmsgbyourcompanynumber' %}','{{ emaildetail.msg }}','{{ m.ourCompanyNumber }}',false, false)">UnlinkByOurNum</button>
                    출원번호 : {{ m.applicationNumber }}
            <button class="btn btn-primary"
                    onclick="linkwithMaster('{% url 'emailsystem:linkemailmsgbyapplnumber' %}','{{ emaildetail.msg }}','{{ m.applicationNumber }}',false, true)">UnlinkByAppl</button>

            <button {% if emaildetail.msgisClassified %}class="btn btn-danger"
                    {% else %}class="btn btn-primary"{% endif %}
                    onclick="setClassfied({{ emaildetail.msg }})">{% if emaildetail.msgisClassified %}미확정{% else %}
                확정{% endif %}</button>
        <p style="margin-left: 5px">
        <table class="basictable">
            {% if forloop.first %}
                {% include 'forinclude/patent/patent_simpleinfo_th.html' with h=masterfield_multiplelang patent=m.patentType nation=m.nationType %}
            {% endif %}
            {% include 'forinclude/patent/patent_simpleinfo_td.html' with data=m patent=m.patentType nation=m.nationType %}
        </table>
        </p>
        </span></p>
        {% if case not in emaildetail.msg.case.all %}
        {% endif %}
        {% for case in m.case.all %}
            {% if case not in msg.case.all %}
                <p style="margin-left: 15px;">사건 이름 : {{ case }}
                    <button onclick="linkcaseortasktomessage('{% url 'case:linkcaseortaskmessage' %}','{{ emaildetail.msg }}','{{ case.id }}','link','case')"
                            class="btn btn-primary">LinkMessage
                    </button>
                </p>
            {% else %}
                <p style="margin-left: 15px;">사건 이름 : {{ case }}
                    <button onclick="linkcaseortasktomessage('{% url 'case:linkcaseortaskmessage' %}','{{ emaildetail.msg }}','{{ case.id }}','unlink','case')"
                            class="btn btn-danger">UnlinkMessage
                    </button>
                </p>
            {% endif %}
            {% for task in case.task.all %}
                {% if task not in msg.task.all %}
                    <p style="margin-left: 30px;">업무 이름 : {{ task }}
                        <button onclick="linkcaseortasktomessage('{% url 'case:linkcaseortaskmessage' %}','{{ emaildetail.msg }}','{{ task.id }}','link','task')"
                                class="btn btn-primary">LinkMessage
                        </button>
                    </p>
                {% else %}
                    <p style="margin-left: 30px;">업무 이름 : {{ task }}
                        <button onclick="linkcaseortasktomessage('{% url 'case:linkcaseortaskmessage' %}','{{ emaildetail.msg }}','{{ task.id }}','unlink','task')"
                                class="btn btn-danger">UnlinkMessage
                        </button>
                    </p>
                {% endif %}

            {% endfor %}
        {% endfor %}

    {% endfor %}
    {% if revenue_invoice %}
        <p>청구서 번호 : {{ revenue_invoice }}</p>
    {% endif %}
    <p class="emailtitle">연결된 사건</p>
    {% for c in msg.case.all %}
        {{ c }}
    {% endfor %}
    <p class="emailtitle">연결된 업무</p>
    {% for c in msg.task.all %}
        {{ c }}
    {% endfor %}
</div>
<br>
<button class="btn-light" onclick="HideShowUsing('emaildetail_function')">기능</button>
<br>
<br>
<div style="display: none" class="emaildetail_function">

    <p class="emailtitle">본문 추출 출원</p>
    {% for s in searchedourcomnumber %}
        <span>{{ s }}</span>
    {% endfor %}
    {% for s in searchedapplno %}
        <span>{{ s }}</span>
    {% endfor %}
    <br>
    <br>
    <p class="emailtitle">검색된 출원 - 미분류</p>
    {% for num in searchedmasternoclassified %}
        <p><span>{{ num.ourCompanyNumber }}
            {% if num.ourCompanyNumber %}
                <button class="btn btn-primary"
                        onclick="linkwithMaster('{% url 'emailsystem:linkemailmsgbyourcompanynumber' %}','{{ emaildetail.msg }}','{{ num.ourCompanyNumber }}',true, false)">LinkByOurNum</button>
            {% endif %}
            </span>
            <span>{{ num.applicationNumber }}
                {% if num.applicationNumber %}
                    <button class="btn btn-primary"
                            onclick="linkwithMaster('{% url 'emailsystem:linkemailmsgbyapplnumber' %}','{{ emaildetail.msg }}','{{ num.applicationNumber }}',true, true)">LinkByAppl</button>
                {% endif %}
                </span>
        </p>
    {% endfor %}
    <br>

    <br>
    <!-- 이메일 메시지 간 re/fw/ack 선택하여 연결 기능, 이메일 ack 발송 기능 -->
    {% load emailsystem_tags %}
    {% include_email_relation emaildetail %}


    <br>
    <!-- 메시지와 case task 연결 기능 -->
    <!--{% include 'forinclude/include_addcase.html' with casetype=casetype emaildetail=emaildetail form=form master=master %}-->
    <form method="post" action="{% url 'case:createcasewithmasterandmsg' %}">
        {% csrf_token %}

        {% include_email_case_form emaildetail.msg form emaildetail.email_file.all %}
        <br>
        <input class="btn btn-primary" type="submit" value="save case">
    </form>
    <br>
    <form method="post" action="{% url 'case:createtaskwithmasterandmsg' %}">
        {% include_email_task_form emaildetail.msg taskform %}
        <br>
        <input class="btn btn-primary" type="submit" value="save task">
    </form>

</div>
<br>
<p class="emailtitle">내용</p><br>
{% if ishtml == "True" %}
    <iframe style="height: 800px; width: 80%" frameBorder="0"
            src="{% url 'emailsystem:emailtextbody' emaildetail.id %}">

    </iframe>

{% else %}

    {% autoescape on %}{{ emaildetail.body }}{% endautoescape %}
{% endif %}
<br>
<button class="btn-light" onclick="HideShowUsing('headerdiv')">헤더</button>
<div class="headerdiv" style="display: none">
    <p>header</p>
    <p style="font-size: 11pt">{{ emaildetail.header }}</p>
</div>
<br>

<div id="dialog">

</div>
<script type="text/javascript">


    window.addEventListener('message', receiveMsgFromParent);

    // 부모로부터 메시지 수신
    function receiveMsgFromParent(e) {


    }

    function sendMsgToParent(msg) {

        window.parent.postMessage(msg, '*');
    }


    $(document).ready(function () {

    });


    function setClassfied(msgid) {

        let formData = new FormData()
        formData.append('msgid', msgid)
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');

        fetch('{% url 'message:emailiframe_setclassfied' %}', {
            method: 'POST',
            body: formData,
            credentials: 'same-origin',
        })
            .then(response => {


                    sendMsgToParent(msgid);


                }
            )
            .catch(() => {
                alert('fail')
            })

    }

    $(function () {

        $(document).tooltip();


        $("#dialog").dialog({
            autoOpen: false, //자동으로 열리지않게

            //"center", "left", "right", "top", "bottom"
            modal: true, //모달대화상자
            resizable: false, //크기 조절 못하게
            buttons: {
                "확인": function () {
                    var pid = $('#pid').text()
                    let formData = new FormData()
                    formData.append('pid', pid)
                    formData.append('searchContent', $("#selecteditem").text())
                    formData.append('searchType', $("#selecteditem").attr('class'))
                    formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
                    fetch('{% url 'message:linkpatentmastermessage' %}', {
                        method: 'POST',
                        body: formData,
                        credentials: 'same-origin',
                    })
                        .then(response => {
                                sendMsgToParent(msgid);

                            }
                        )
                        .catch(() => {
                            alert('fail')
                        })


                    $(this).dialog("close");

                }, "취소": function () {
                    $(this).dialog("close");

                }
            }
        });

        //창 열기 버튼을 클릭했을경우


    });


    function popupdialogbox(e, url) {
        let target = $(e)

        var yourPosition = {
            my: "center top",
            at: "center bottom",
            of: target
        };

        //$( "#dialog" ).dialog( "option", "position", yourPosition );

        $("#dialog").dialog({position: yourPosition});
        $("#dialog").load(url);
        $("#dialog").dialog("open");
    }


    function getfile(e, url) {

        var files = e.target.files;
        files = [...files]
        uploadFile(files, url)

        //var path = files[0].webkitRelativePath;
        //var Folder = path.split("/");

    }

    function uploadFile(files, url) {
        //let url = 'http://127.0.0.1:8000/emailsystem/emailuploading'

        let formData = new FormData()

        for (var i = 0; i < files.length; i++) {
            formData.append('files[]', files[i])
        }
        formData.append('csrfmiddlewaretoken', $('#csrf-helper input[name="csrfmiddlewaretoken"]').attr('value'));
        fetch(url, {
            method: 'POST',
            body: formData,
            credentials: 'same-origin',
        })
            .then(response => {
                    alert('success.')
                    sendMsgToParent(msgid);
                }
            )
            .catch(() => {
                alert('fail')
            })
    }

    function changeHTML(action, val) {

        let formData = new FormData()

        formData.append('isHTML', val)
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        fetch(action, {
            method: 'POST',
            body: formData,
            credentials: 'same-origin',
        })
            .then(response => {

                    sendMsgToParent(msgid);
                }
            )
            .catch(() => {
                alert('fail')
            })

    }

    function linkcaseortasktomessage(action, mid, objid, func, type) {

        let formData = new FormData()
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        formData.append('msgid', mid)
        formData.append('objid', objid)
        formData.append('func', func)
        formData.append('type', type)
        fetch(action, {
            method: 'POST',
            body: formData,
            credentials: 'same-origin',
        })
            .then(response => {

                    sendMsgToParent(mid);
                }
            )
            .catch(() => {
                alert('fail')
            })

    }
    function linkwithMaster(url, msgid, var_, link, isAppNo)
    {

        let formData = new FormData()
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        formData.append('msgid', msgid)
        if (isAppNo)
        {
            formData.append('applno', var_)
        }
        else
        {
            formData.append('ourcomnumber', var_)
        }
        formData.append('link', link)

        fetch(url, {
            method: 'POST',
            body: formData,
            credentials: 'same-origin',
        })
            .then(response => {

                    sendMsgToParent(msgid);
                }
            )
            .catch(() => {
                alert('fail')
            })

    }
</script>